# Switch Class Driver
obj-$(CONFIG_SWITCH_FSA9685) += fsa9685.o
obj-$(CONFIG_SWITCH_FSA9685) += rt8979.o
obj-$(CONFIG_SWITCH_FSA9685) += usbswitch_fsa9685.o
obj-$(CONFIG_SWITCH_FSA9685) += usbswitch_rt8979.o
obj-$(CONFIG_SWITCH_FSA9685) += rt8979_bc12.o
obj-$(CONFIG_SWITCH_FSA9685) += fsa9685_bc12.o
obj-$(CONFIG_SWITCH_FSA9685) += switch_chip_i2c.o
obj-$(CONFIG_SWITCH_FSA9685) += switch_charger_protocol.o
obj-$(CONFIG_SWITCH_FSA9685) += switch_control.o
obj-$(CONFIG_SWITCH_FSA9685) += switch_interface.o
obj-$(CONFIG_SWITCH_FSA9685) += rt8979_osc.o
obj-$(CONFIG_SWITCH_FSA9685) += fsa9685_accp.o
obj-$(CONFIG_SWITCH_FSA9685) += rt8979_accp.o