obj-$(CONFIG_SAMSUNG_TS_KIT_3_0) += sec_driver.o
sec_driver-objs += sec_ts.o sec_ts_fw.o sec_ts_fn.o sec_ts_only_vendor.o
EXTRA_CFLAGS += -Iarch/arm/mach-honor
EXTRA_CFLAGS += -Idrivers/honor/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
EXTRA_CFLAGS += -Idrivers/devkit/lcdkit/lcdkit3.0/kernel/common/include
EXTRA_CFLAGS += -Idrivers/devkit/tpkit/3_0
