/*---------------------------------------------------------------------------
 * This file is autogenerated file using huawei LCD parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * Parser location: vendor/huawei/chipset_common/devkit/lcdkit/tools 
 *---------------------------------------------------------------------------*/

#ifndef _LCDKIT_EFFECT__H_
#define _LCDKIT_EFFECT__H_


#include "plat_effect_para.h"

/*---------------------------------------------------------------------------*/
/* static panel selection variable                                           */
/*---------------------------------------------------------------------------*/
enum {
LNA_190_C07_6P67_PANEL,
LNA_310_C06_6P67_PANEL,
LNA_310_C07_6P67_PANEL,
BLK_190_C07_6P7_PANEL,
BLK_310_C06_6P7_PANEL,
BLK_310_D06_6P7_PANEL,
BLK_290_F01_6P7_PANEL,
BLS_190_C07_1_6P7_PANEL,
BLS_310_C06_1_6P7_PANEL,
BLS_290_F01_1_6P7_PANEL,
ADA_190_C08_6P76_PANEL,
ADA_290_C08_6P76_PANEL,
ADA_290_F01_6P76_PANEL,
MLA_190_C08_2_6P76_PANEL,
MLA_290_C08_2_6P76_PANEL,
MLA_290_F01_2_6P76_PANEL,
MLS_190_C08_3_6P76_PANEL,
MLS_290_C08_3_6P76_PANEL,
MLS_290_F01_3_6P76_PANEL,
STL_310_C08_6P94_PANEL,
STL_AUO_DEF_6P94_PANEL,
PSD_310_C08_P_6P94_PANEL,
PSD_192_C08_P_6P94_PANEL,
PSD_290_C08_P_6P94_PANEL,
PSD_AUO_DEF_6P94_PANEL,
PSD_310_C11_2P14_PANEL,
PSD_350_C11_2P14_PANEL,
PSD_AUO_DEF_2P14_PANEL,
BTKR_190_20D_11P45_PANEL,
BTKR_290_20D_11P45_PANEL,
BTKR_190_607_11P45_PANEL,
BTKR_AUO_DEF_11P45_PANEL,
DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
INVALID_PANEL_ID,
};


/*---------------------------------------------------------------------------*/
/* static panel board mapping variable                                           */
/*---------------------------------------------------------------------------*/
struct lcd_kit_board_map {
    uint32_t lcd_id;
    char *panel_compatible;
    uint32_t product_id;
};

static struct lcd_kit_board_map lcd_kit_map[] = {
    {LNA_190_C07_6P67_PANEL, "190_c07_6p67", 1000},
    {LNA_310_C06_6P67_PANEL, "310_c06_6p67", 1000},
    {LNA_310_C07_6P67_PANEL, "310_c07_6p67", 1000},
    {BLK_190_C07_6P7_PANEL, "190_c07_6p7", 2000},
    {BLK_310_C06_6P7_PANEL, "310_c06_6p7", 2000},
    {BLK_310_D06_6P7_PANEL, "310_d06_6p7", 2000},
    {BLK_290_F01_6P7_PANEL, "290_f01_6p7", 2000},
    {BLS_190_C07_1_6P7_PANEL, "190_c07_1_6p7", 2001},
    {BLS_310_C06_1_6P7_PANEL, "310_c06_1_6p7", 2001},
    {BLS_290_F01_1_6P7_PANEL, "290_f01_1_6p7", 2001},
    {ADA_190_C08_6P76_PANEL, "190_c08_6p76", 2100},
    {ADA_290_C08_6P76_PANEL, "290_c08_6p76", 2100},
    {ADA_290_F01_6P76_PANEL, "290_f01_6p76", 2100},
    {MLA_190_C08_2_6P76_PANEL, "190_c08_2_6p76", 2101},
    {MLA_290_C08_2_6P76_PANEL, "290_c08_2_6p76", 2101},
    {MLA_290_F01_2_6P76_PANEL, "290_f01_2_6p76", 2101},
    {MLS_190_C08_3_6P76_PANEL, "190_c08_3_6p76", 2102},
    {MLS_290_C08_3_6P76_PANEL, "290_c08_3_6p76", 2102},
    {MLS_290_F01_3_6P76_PANEL, "290_f01_3_6p76", 2102},
    {STL_310_C08_6P94_PANEL, "310_c08_6p94", 3000},
    {STL_AUO_DEF_6P94_PANEL, "auo_def_6p94", 3000},
    {PSD_310_C08_P_6P94_PANEL, "310_c08_p_6p94", 3001},
    {PSD_192_C08_P_6P94_PANEL, "192_c08_p_6p94", 3001},
    {PSD_290_C08_P_6P94_PANEL, "290_c08_p_6p94", 3001},
    {PSD_AUO_DEF_6P94_PANEL, "auo_def_6p94", 3001},
    {PSD_310_C11_2P14_PANEL, "310_c11_2p14", 3001},
    {PSD_350_C11_2P14_PANEL, "350_c11_2p14", 3001},
    {PSD_AUO_DEF_2P14_PANEL, "auo_def_2p14", 3001},
    {BTKR_190_20D_11P45_PANEL, "190_20d_11p45", 4000},
    {BTKR_290_20D_11P45_PANEL, "290_20d_11p45", 4000},
    {BTKR_190_607_11P45_PANEL, "190_607_11p45", 4000},
    {BTKR_AUO_DEF_11P45_PANEL, "auo-def-11p45", 4000},
    {DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "auo_otm1901a_5p2_1080p_video_default", 0},
};

static void lcd_kit_effect_get_data(uint8_t panel_id, struct hisi_panel_info* pinfo)
{
    if (pinfo->gamma_support == 1)
    {
        pinfo->gamma_lut_table_R = plat_gamma_lut_table_R;
        pinfo->gamma_lut_table_G = plat_gamma_lut_table_G;
        pinfo->gamma_lut_table_B = plat_gamma_lut_table_B;
        pinfo->gamma_lut_table_len = ARRAY_SIZE(plat_gamma_lut_table_R);
        pinfo->igm_lut_table_R = plat_igm_lut_table_R;
        pinfo->igm_lut_table_G = plat_igm_lut_table_G;
        pinfo->igm_lut_table_B = plat_igm_lut_table_B;
        pinfo->igm_lut_table_len = ARRAY_SIZE(plat_igm_lut_table_R);
        pinfo->gmp_lut_table_low32bit = &plat_gmp_lut_table_low32bit[0][0][0];
        pinfo->gmp_lut_table_high4bit = &plat_gmp_lut_table_high4bit[0][0][0];
        pinfo->gmp_lut_table_len = ARRAY_3_SIZE(plat_gmp_lut_table_low32bit);
        pinfo->xcc_table = plat_xcc_table;
        pinfo->xcc_table_len = ARRAY_SIZE(plat_xcc_table);
    }
    switch (panel_id) {
    default:
        LCD_KIT_INFO("Panel ID not detected %d\n", panel_id);
        break;
    }
}

static uint8_t lcd_kit_get_panel_id(uint32_t product_id, char* compatible)
{
    uint8_t lcd_panel_id = DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL;
    int i = 0;
    int len = strlen(compatible);
    int length = 0;
    for (i = 0; i < ARRAY_SIZE(lcd_kit_map); ++i) {
        length = strlen(lcd_kit_map[i].panel_compatible);
        if ((lcd_kit_map[i].product_id == product_id) && !strncmp(lcd_kit_map[i].panel_compatible, compatible, (length > len?length:len))){
            lcd_panel_id = lcd_kit_map[i].lcd_id;
            break;
        }
    }

    HISI_FB_INFO("lcd_panel_id = %d\n", lcd_panel_id);
    return lcd_panel_id;
}


#endif /*_LCDKIT_EFFECT__H_*/
