# Makefile for the mipibridge.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_HUAWEI_MIPIBRIDGE) += mipibridge_driver.o
obj-$(CONFIG_HUAWEI_MIPIBRIDGE) += mipibridge_uart.o
obj-$(CONFIG_HUAWEI_MIPIBRIDGE) += mipibridge_spi.o
obj-$(CONFIG_HUAWEI_MIPIBRIDGE) += jw/hv6100.o
