obj-$(CONFIG_HONOR_EMCOM) += emcom_netlink.o
obj-$(CONFIG_HONOR_EMCOM) += emcom_utils.o
obj-$(CONFIG_TCP_ARGO) += argo/
obj-$(CONFIG_HONOR_XENGINE) += xengine/
obj-$(CONFIG_HONOR_EMCOM) += smartcare/
obj-$(CONFIG_HONOR_NWEVAL) += nweval/
obj-$(CONFIG_HONOR_OPMP) += opmp/
obj-$(CONFIG_HONOR_EMCOM) += nstack/