subdir-ccflags-y += -Wall -Werror
obj-$(CONFIG_EL3_PA_TEST) += el3_pa_test.o
obj-$(CONFIG_BTI_TEST) += bti_test.o
obj-$(CONFIG_BTI_TEST) += bti_testcase.o
obj-$(CONFIG_PAC_TEST) += pac_test.o
obj-$(CONFIG_PAC_TEST) += pac_testcase.o
