#ifndef __NPU_DDR_MAP_H__
#define __NPU_DDR_MAP_H__ 
#include <global_ddr_map.h>
#define NPU_TEEOS_RESMEM_SIZE 0x1780000
#define NPU_TEEOS_PAGETABLE_SIZE 0x0180000
#define NPU_TEEOS_RESMEM_BASE (RESERVED_TD_FACE_DETECT_PHYMEM_BASE + (RESERVED_TD_FACE_DETECT_PHYMEM_SIZE - (NPU_TEEOS_RESMEM_SIZE + NPU_TEEOS_PAGETABLE_SIZE)))
#define NPU_TEEOS_PAGETABLE_BASE (RESERVED_TD_FACE_DETECT_PHYMEM_BASE + (RESERVED_TD_FACE_DETECT_PHYMEM_SIZE - NPU_TEEOS_PAGETABLE_SIZE))
#ifdef NPU_TSCH_USE_DMMU_MEM
    #define NPU_NONSEC_RESERVED_DDR_BASE_ADDR 0xC0000000
#else
    #define NPU_NONSEC_RESERVED_DDR_BASE_ADDR (RESERVED_NPU_AI_TS_FW_PHYMEM_BASE)
#endif
#define NPU_NONSEC_RESERVED_MEMORY_SIZE 0xD00000
#define NPU_SEC_RESERVED_DDR_BASE_ADDR (RESERVED_NPU_SEC_PHYMEM_BASE)
#define NPU_SEC_RESERVED_DDR_SIZE 0xA00000
#define NPU_TS_CPU_UNRST_ADDR 0xC0000000
enum tag_reserved_memory_idx {
    NPU_TSCPU_FW_IDX = 0,
    NPU_CTRL_INFO_IDX = 1,
    NPU_LOG_MEM_IDX = 2,
    NPU_BBOX_MEM_IDX = 3,
    NPU_COMM_SQCQ_RESMEM_IDX = 4,
    NPU_DFX_SQCQ_RESMEM_IDX = 5,
    NPU_HWTS_SDMA_SQCQ_RESMEM_IDX = 6,
    NPU_TS_SDMA_SQCQ_RESMEM_IDX = 7,
    NPU_TS_CONFIG_RESMEM_IDX = 8,
    NPU_NPU_CFG_IDX = 9,
    NPU_PROF_MEM_IDX = 10,
    NPU_MAX_RESMEM_IDX = 11,
};
enum tag_npu_nonsec_reserved_ddr {
    NPU_NS_TSCPU_FW_SIZE = 0x400000,
    NPU_NS_CTRL_INFO_SIZE = 0x80000,
    NPU_NS_LOG_SIZE = 0x80000,
    NPU_NS_BBOX_SIZE = 0x40000,
    NPU_NS_COMM_SQCQ_SIZE = 0x200000,
    NPU_NS_DFX_SQCQ_SIZE = 0x80000,
    NPU_NS_HWTS_SDMA_SQ_SIZE = 0x20000,
    NPU_NS_TS_SDMA_SQCQ_SIZE = 0x20000,
    NPU_NS_TS_CONFIG_SIZE = 0x40000,
    NPU_NS_NPU_CONFIG_SIZE = 0x1000,
};
#define NPU_NS_TSCPU_RESERVED_SIZE 0x900000
#define NPU_NS_TSCPU_FW_BASE_ADDR (NPU_NONSEC_RESERVED_DDR_BASE_ADDR)
#define NPU_NS_CTRL_INFO_BASE_ADDR (NPU_NS_TSCPU_FW_BASE_ADDR + NPU_NS_TSCPU_FW_SIZE)
#define NPU_NS_LOG_BASE_ADDR (NPU_NS_CTRL_INFO_BASE_ADDR + NPU_NS_CTRL_INFO_SIZE)
#define NPU_NS_BBOX_BASE_ADDR (NPU_NS_LOG_BASE_ADDR + NPU_NS_LOG_SIZE)
#define NPU_NS_COMM_SQCQ_BASE_ADDR (NPU_NS_BBOX_BASE_ADDR + NPU_NS_BBOX_SIZE)
#define NPU_NS_DFX_SQCQ_BASE_ADDR (NPU_NS_COMM_SQCQ_BASE_ADDR + NPU_NS_COMM_SQCQ_SIZE)
#define NPU_NS_HWTS_SDMA_SQ_BASE_ADDR (NPU_NS_DFX_SQCQ_BASE_ADDR + NPU_NS_DFX_SQCQ_SIZE)
#define NPU_NS_TS_SDMA_SQCQ_BASE_ADDR (NPU_NS_HWTS_SDMA_SQ_BASE_ADDR + NPU_NS_HWTS_SDMA_SQ_SIZE)
#define NPU_NS_TS_CONFIG_BASE_ADDR (NPU_NS_TS_SDMA_SQCQ_BASE_ADDR + NPU_NS_TS_SDMA_SQCQ_SIZE)
#define NPU_NS_NPU_CONFIG_BASE_ADDR (NPU_NS_TS_CONFIG_BASE_ADDR + NPU_NS_TS_CONFIG_SIZE)
enum tag_npu_sec_reserved_ddr {
    NPU_S_NPU_CONFIG_SIZE = 0x1000,
    NPU_S_HWTS_SQCQ_SIZE = 0x400000,
    NPU_S_SMMU_QUEUE_SIZE = 0xE000,
};
#define NPU_S_NPU_CONFIG_BASE_ADDR (NPU_SEC_RESERVED_DDR_BASE_ADDR)
#define NPU_S_HWTS_SQCQ_BASE_ADDR (NPU_S_NPU_CONFIG_BASE_ADDR + NPU_S_NPU_CONFIG_SIZE)
#define NPU_S_SMMU_QUEUE_BASE_ADDR (NPU_S_HWTS_SQCQ_BASE_ADDR + NPU_S_HWTS_SQCQ_SIZE)
#endif
