/****************************************************
CAUTION : Auto Generated by Perl based on *.xml
		so,don't modify this file manually!
****************************************************/
#ifndef LOWPM_GPIO_AUTO_GEN_H
#define LOWPM_GPIO_AUTO_GEN_H

#define CHIPID_DIG_NUMS 4

#define LOW_POWER(imob, imo, imv, icob, ico, icv, gpiodrv, gpiog, gpiob, gpiod, gpiov, func0, func1, func2, func3, logic, core) \
{				\
	.iomg_base = imob, .iomg_offset = imo,  .iomg_val = imv,   \
	.iocg_base = icob, .iocg_offset = ico,  .iocg_val  = icv,   \
	.iodriver  = gpiodrv,   \
	.gpio_group_id    = gpiog, .ugpio_bit = gpiob,   \
	.gpio_dir  = gpiod, .gpio_val  = gpiov,   \
	.gpio_func0  = func0, .gpio_func1  = func1,   \
	.gpio_func2  = func2, .gpio_func3  = func3,   \
	.gpio_logic = logic,  .gpio_core  = core   \
}


#define FUNC0		0X0
#define FUNC1		0X1
#define FUNC2		0X2
#define FUNC3		0X3
#define FUNC4		0X4
#define FUNC5		0X5
#define FUNC6		0X6
#define FUNC7		0X7

#define NOPULL		0X0
#define PULLUP		0X1
#define PULLDOWN	0X2

#define PULLBK	0X3

#define OUT			1
#define IN			0

#define LOW			0x0
#define HIGH		0x1

#define N			-1

#define CFG_END			0xFF

#define GPIOMUX_2mA_1	0x00
#define GPIOMUX_4mA_1	0x10
#define GPIOMUX_6mA_1	0x20
#define GPIOMUX_8mA_1	0x30
#define GPIOMUX_10mA_1	0x40
#define GPIOMUX_12mA_1	0x50
#define GPIOMUX_14mA_1	0x60
#define GPIOMUX_16mA_1	0x70
#define GPIOMUX_5mA_2	0x00
#define GPIOMUX_7mA_2	0x10
#define GPIOMUX_9mA_2	0x20
#define GPIOMUX_11mA_2	0x30
#define GPIOMUX_14mA_2	0x40
#define GPIOMUX_16mA_2	0x50
#define GPIOMUX_18mA_2	0x60
#define GPIOMUX_20mA_2	0x70
#define GPIOMUX_22mA_2	0x80
#define GPIOMUX_25mA_2	0x90
#define GPIOMUX_27mA_2	0xA0
#define GPIOMUX_29mA_2	0xB0
#define GPIOMUX_32mA_2	0xC0
#define GPIOMUX_34mA_2	0xD0
#define GPIOMUX_36mA_2	0xE0
#define GPIOMUX_38mA_2	0xF0
#define DRIVER_NONSET	0xFF
static char pulltype[][9] = {"NP", "PU", "PD", "BK"};


struct iocfg_lp {
	unsigned int iomg_base;
	int iomg_offset;
	int iomg_val;
	unsigned int iocg_base;
	int iocg_offset;
	int iocg_val;
	unsigned int iodriver;
	unsigned int gpio_group_id;
	unsigned int ugpio_bit;
	unsigned int gpio_dir;
	unsigned int gpio_val;
	const char *gpio_func0;
	const char *gpio_func1;
	const char *gpio_func2;
	const char *gpio_func3;
	const char *gpio_logic;
	char gpio_core[5];
};


struct iocfg_lp_entry {
	int chipid[CHIPID_DIG_NUMS];
	char boardname[40];
	struct iocfg_lp *iocfg;
};


struct iocfg_lp burbank_fpga_es_hisi_iocfg_lookups[] = {
	/*IOMGBASE        IOMG        FUNCTION       IOCGBASE        IOCG        PULL_TYPE       GPIO_GROUP        GROUP_OFFSET        Direction        Output_value      GPIO_LOGIC      CORE*/
	//CFG_END
	LOW_POWER(0,	CFG_END,	N,	0,	0,	N,	DRIVER_NONSET,	0,	0,	N,	N,	"-",	"-",	"-",	"-",	"-",	"-"),
};

struct iocfg_lp burbank_fpga_cs_hisi_iocfg_lookups[] = {
	/*IOMGBASE        IOMG        FUNCTION       IOCGBASE        IOCG        PULL_TYPE       GPIO_GROUP        GROUP_OFFSET        Direction        Output_value      GPIO_LOGIC      CORE*/
	//CFG_END
	LOW_POWER(0,	CFG_END,	N,	0,	0,	N,	DRIVER_NONSET,	0,	0,	N,	N,	"-",	"-",	"-",	"-",	"-",	"-"),
};

struct iocfg_lp burbank_emulator_es_hisi_iocfg_lookups[] = {
	/*IOMGBASE        IOMG        FUNCTION       IOCGBASE        IOCG        PULL_TYPE       GPIO_GROUP        GROUP_OFFSET        Direction        Output_value      GPIO_LOGIC      CORE*/
	//CFG_END
	LOW_POWER(0,	CFG_END,	N,	0,	0,	N,	DRIVER_NONSET,	0,	0,	N,	N,	"-",	"-",	"-",	"-",	"-",	"-"),
};

struct iocfg_lp burbank_chip_es_hisi_iocfg_lookups[] = {
	/*IOMGBASE        IOMG        FUNCTION       IOCGBASE        IOCG        PULL_TYPE       GPIO_GROUP        GROUP_OFFSET        Direction        Output_value      GPIO_LOGIC      CORE*/
	//CFG_END
	LOW_POWER(0,	CFG_END,	N,	0,	0,	N,	DRIVER_NONSET,	0,	0,	N,	N,	"-",	"-",	"-",	"-",	"-",	"-"),
};

struct iocfg_lp burbank_emulator_cs_hisi_iocfg_lookups[] = {
	/*IOMGBASE        IOMG        FUNCTION       IOCGBASE        IOCG        PULL_TYPE       GPIO_GROUP        GROUP_OFFSET        Direction        Output_value      GPIO_LOGIC      CORE*/
	//CFG_END
	LOW_POWER(0,	CFG_END,	N,	0,	0,	N,	DRIVER_NONSET,	0,	0,	N,	N,	"-",	"-",	"-",	"-",	"-",	"-"),
};

struct iocfg_lp burbank_chip_cs_hisi_iocfg_lookups[] = {
	/*IOMGBASE        IOMG        FUNCTION       IOCGBASE        IOCG        PULL_TYPE       GPIO_GROUP        GROUP_OFFSET        Direction        Output_value      GPIO_LOGIC      CORE*/
	//CFG_END
	LOW_POWER(0,	CFG_END,	N,	0,	0,	N,	DRIVER_NONSET,	0,	0,	N,	N,	"-",	"-",	"-",	"-",	"-",	"-"),
};




struct iocfg_lp_entry iocfg_tables[] = {
	{ {2, 8, 6, 6}, "burbank_fpga_es", burbank_fpga_es_hisi_iocfg_lookups },
	{ {2, 8, 6, 8}, "burbank_fpga_cs", burbank_fpga_cs_hisi_iocfg_lookups },
	{ {2, 8, 6, 10}, "burbank_emulator_es", burbank_emulator_es_hisi_iocfg_lookups },
	{ {2, 8, 6, 0}, "burbank_chip_es", burbank_chip_es_hisi_iocfg_lookups },
	{ {2, 8, 6, 11}, "burbank_emulator_cs", burbank_emulator_cs_hisi_iocfg_lookups },
	{ {2, 8, 6, 1}, "burbank_chip_cs", burbank_chip_cs_hisi_iocfg_lookups },
	{ {-1, -1, -1, -1}, "-", 0}
};



#endif
