honor_scm-y	:= scm_main.o \
		scm_sub_modules.o \
		scm_internal.o \
		scm_task_status.o \
		scm_policy_shrinker.o \
		scm_policy_reclaim.o \
		scm_policy_qos_pool.o \
		scm_policy_misc.o


obj-$(CONFIG_HONOR_SCM)	+=	honor_scm.o
