#ifndef __LPMCU_DIAGINFO_MAP
#define __LPMCU_DIAGINFO_MAP(x,y,z) 
#endif
#include <bbox_diaginfo_id_def.h>
__LPMCU_DIAGINFO_MAP(LPM3_DDR_FAIl, 3, "PLL lock fail:")
__LPMCU_DIAGINFO_MAP(CLOCK_PLL_LPMCU, 3, "PLL lock fail:")
__LPMCU_DIAGINFO_MAP(ACPU_LIT_AVS_VAL, 6, "LIT_AVS_VAL:")
__LPMCU_DIAGINFO_MAP(ACPU_MID_AVS_VAL, 6, "MID_AVS_VAL:")
__LPMCU_DIAGINFO_MAP(ACPU_BIG_AVS_VAL, 6, "BIG_AVS_VAL:")
__LPMCU_DIAGINFO_MAP(LPM3_DDR_PA_SENSOR, 6, "PASENSOR:")
__LPMCU_DIAGINFO_MAP(LPM3_DDR_TRAINING, 6, "TRAINING:")
