#ifndef __PLATFORM_MEMORY_DEF_H__
#define __PLATFORM_MEMORY_DEF_H__ 
#include <global_ddr_map.h>
#define ATF_BL31_BASE ATF_RESERVED_BL31_PHYMEM_BASE
#define ATF_BL31_RAM_ADDR ATF_BL31_BASE
#define ATF_BL31_RAM_SIZE (0xE0000)
#define HISI_BL31_LOG_USER_ADDR (ATF_BL31_BASE + ATF_BL31_RAM_SIZE)
#define HISI_BL31_LOG_USER_SIZE (0x20000)
#define HISI_BL31_DATA_START (HISI_BL31_LOG_USER_ADDR + HISI_BL31_LOG_USER_SIZE)
#define ATF_BL31_PARAMS_FROM_FASTBOOT_PARAMS_ADDR HISI_BL31_DATA_START
#define ATF_BL31_PARAMS_FROM_FASTBOOT_PARAMS_SIZE (0x110)
#define BL31_RPMB_KEY_INFO_ADDR (ATF_BL31_PARAMS_FROM_FASTBOOT_PARAMS_ADDR + \
                ATF_BL31_PARAMS_FROM_FASTBOOT_PARAMS_SIZE)
#define BL31_RPMB_KEY_INFO_SIZE (0x20)
#define BL31_RPMB_CRYPTOGRAPHIC_KEY_ADDR (BL31_RPMB_KEY_INFO_ADDR + \
                BL31_RPMB_KEY_INFO_SIZE)
#define BL31_RPMB_CRYPTOGRAPHIC_KEY_SIZE (0x20)
#define ATF_BL31_HUK_CODE_ADDR (BL31_RPMB_CRYPTOGRAPHIC_KEY_ADDR + BL31_RPMB_CRYPTOGRAPHIC_KEY_SIZE)
#define ATF_BL31_HUK_CODE_SIZE (0x20)
#define BL31_RPMB_KEY_ADDR (ATF_BL31_HUK_CODE_ADDR + ATF_BL31_HUK_CODE_SIZE)
#define BL31_RPMB_KEY_SIZE (0x20)
#define BL31_DDRC_INFO_ADDR (BL31_RPMB_KEY_ADDR + BL31_RPMB_KEY_SIZE)
#define BL31_DDRC_INFO_SIZE (0x200)
#define BL31_UFS_KEY_ADDR (BL31_DDRC_INFO_ADDR + BL31_DDRC_INFO_SIZE)
#define BL31_UFS_KEY_SIZE (0x800)
#define BL31_RPMB_DEVICE_INFO_ADDR (BL31_UFS_KEY_ADDR + BL31_UFS_KEY_SIZE)
#define BL31_RPMB_DEVICE_INFO_SIZE (0x28)
#define BL31_RPMB_BOOT_INFO_ADDR (BL31_RPMB_DEVICE_INFO_ADDR + BL31_RPMB_DEVICE_INFO_SIZE)
#define BL31_RPMB_BOOT_INFO_SIZE (0x20)
#define BL31_FASTBOOT_HITEST_MNTN_ADDR (BL31_RPMB_BOOT_INFO_ADDR + BL31_RPMB_BOOT_INFO_SIZE)
#define BL31_FASTBOOT_HITEST_MNTN_SIZE (0x20)
#define SECINFO_CTX_DDR_ADDR (BL31_FASTBOOT_HITEST_MNTN_ADDR + BL31_FASTBOOT_HITEST_MNTN_SIZE)
#define SECINFO_CTX_DDR_SIZE (0x100)
#define ATF_BL31_RESERVE_MEM_ADDR (SECINFO_CTX_DDR_ADDR + SECINFO_CTX_DDR_SIZE)
#define ATF_BL31_RESERVE_MEM_SIZE (0x308)
#define BL31_ATF_TEE_SHMEM_ADDR (ATF_BL31_RESERVE_MEM_ADDR + ATF_BL31_RESERVE_MEM_SIZE)
#define BL31_ATF_TEE_SHMEM_SIZE (0x1000)
#define BL31_GENERAL_SEE_ADDR (BL31_ATF_TEE_SHMEM_ADDR + BL31_ATF_TEE_SHMEM_SIZE)
#define BL31_GENERAL_SEE_SIZE (0x4FE000)
#define ATF_BL31_SIZE (ATF_RESERVED_BL31_PHYMEM_SIZE - BL31_GENERAL_SEE_SIZE)
#define ATF_BL31_LOG_ADDR HISI_RESERVED_BL31_NS_PHYMEM_BASE
#define ATF_BL31_LOG_SIZE HISI_RESERVED_BL31_NS_PHYMEM_SIZE
#define BL31_KERNEL_SHMEM_ADDR (ATF_SUB_RESERVED_BL31_SHARE_MEM_PHYMEM_BASE + 0x3000)
#define BL31_KERNEL_SHMEM_SIZE 0x2000
#define ATF_BL2_RAM_BASE (ATF_RESERVED_BL2_PHYMEM_BASE)
#define ATF_BL2_RAM_SIZE (ATF_RESERVED_BL2_PHYMEM_SIZE)
#define ATF_BL2_RAM_END (ATF_BL2_RAM_BASE + ATF_BL2_RAM_SIZE)
#define ATF_BL2_LOG_SIZE (ATF_SUB_RESERVED_BL2_LOG_MEM_PHYMEM_SIZE)
#define ATF_BL2_LOG_ADDR (ATF_SUB_RESERVED_BL2_LOG_MEM_PHYMEM_BASE)
#define ATF_BL2_SHMEM_SIZE 0x10000
#define ATF_BL2_SHMEM_ADDR (ATF_BL2_RAM_END - ATF_BL2_SHMEM_SIZE)
#define ATF_BL2_CC_DATA_SIZE 0x100000
#define ATF_BL2_CC_DATA_ADDR (ATF_BL2_SHMEM_ADDR - ATF_BL2_CC_DATA_SIZE)
#define ATF_BL2_DDR_SHMEM_SIZE 0x5000
#define ATF_BL2_DDR_SHMEM_ADDR (ATF_BL2_CC_DATA_ADDR - ATF_BL2_DDR_SHMEM_SIZE)
#define ATF_BL2_EFUSE_SHMEM_SIZE 0x1000
#define ATF_BL2_EFUSE_SHMEM_ADDR (ATF_BL2_DDR_SHMEM_ADDR - ATF_BL2_EFUSE_SHMEM_SIZE)
#define ATF_BL2_SHMEM_RESERVE_SIZE (0x10000 - 0x5000 - 0x1000)
#define ATF_BL2_SHMEM_RESERVE_ADDR (ATF_BL2_EFUSE_SHMEM_ADDR - ATF_BL2_SHMEM_RESERVE_SIZE)
#define ATF_BL2_SECRAM_END (ATF_BL2_SHMEM_RESERVE_ADDR)
#define ATF_BL2_CC_PAL_SIZE 0x100000
#define ATF_BL2_CC_PAL_ADDR (ATF_BL2_SECRAM_END - ATF_BL2_CC_PAL_SIZE)
#endif
