#ifndef __CPU_TOPOLOGY_H_
#define __CPU_TOPOLOGY_H_ 
#define MPIDR_OFFSET 0x8
#define MPIDR_WIDTH 0x4
#define LIT_CLUSTER_CORE_NUM 0x4
#define MID_CLUSTER_CORE_NUM 0x3
#define BIG_CLUSTER_CORE_NUM 0x1
#define LIT_CLUSTER_CORE_BASE 0x0
#define MID_CLUSTER_CORE_BASE 0x4
#define BIG_CLUSTER_CORE_BASE 0x7
#define BD3_CORE_OFFSET 0x0
#define BD3_CORE_WIDTH 0x8
#define BD3_CLUSTER_OFFSET 0x8
#define BD3_CLUSTER_WIDTH 0x8
#endif
