#ifndef __CPU_SERVICES_ID_H__
#define __CPU_SERVICES_ID_H__ 
enum cpu_service_idx {
 BL2_CORE_PWRCTRL,
 BL2_CPU_GOTO_WFI,
 BL2_CPU_SVFD_TRIM,
 BL2_CPU_MOUDLE_INIT,
 BL2_CPU_LOGIC_VOLT_UPDATE,
 BL2_CPU_VOLT_SELF_HEALING,
 CPU_SERVICE_IDX_MAX,
};
#endif
