#ifndef _HI_FASTBOOT_MEMORY_MAP_INCLUDE_H_
#define _HI_FASTBOOT_MEMORY_MAP_INCLUDE_H_ 
#include <global_ddr_map.h>
#define RESERVED_FASTBOOT_PHYMEM_BASE RESERVED_FASTBOOT_CMA_PHYMEM_BASE
#define RESERVED_FASTBOOT_PHYMEM_SIZE 0x600000
#define RESERVED_FASTBOOT_PHYMEM_TOP (RESERVED_FASTBOOT_PHYMEM_BASE \
                                                    + RESERVED_FASTBOOT_PHYMEM_SIZE)
#define RESERVED_FASTBOOT_VRL_SIZE 0x2000
#define RESERVED_FASTBOOT_VRL_BASE (RESERVED_FASTBOOT_PHYMEM_TOP \
                                                    - RESERVED_FASTBOOT_VRL_SIZE)
#define RESERVED_FASTBOOT_STACK_SIZE 0x10000
#define RESERVED_FASTBOOT_STACK_BASE RESERVED_FASTBOOT_VRL_BASE
#ifdef CONFIG_HISI_GCOV_FASTBOOT
#define RESERVED_FASTBOOT_RESERVE_SIZE 0x0
#else
#define RESERVED_FASTBOOT_RESERVE_SIZE 0x80000
#endif
#define RESERVED_FASTBOOT_RESERVE_BASE (RESERVED_FASTBOOT_VRL_BASE \
                                                    - RESERVED_FASTBOOT_RESERVE_SIZE)
#define RESERVED_FASTBOOT_RUNMEM_BASE RESERVED_FASTBOOT_PHYMEM_BASE
#define RESERVED_FASTBOOT_RUNMEN_SIZE (RESERVED_FASTBOOT_PHYMEM_SIZE \
                                                    - RESERVED_FASTBOOT_VRL_SIZE \
                                                    - RESERVED_FASTBOOT_STACK_SIZE \
                                                    - RESERVED_FASTBOOT_RESERVE_SIZE)
#define RESERVED_FASTBOOT_HEAP_CACHE_BASE RESERVED_FASTBOOT_PHYMEM_TOP
#define RESERVED_FASTBOOT_HEAP_CACHE_SIZE 0x1E00000
#define RESERVED_FASTBOOT_HEAP_CACHE_TOP (RESERVED_FASTBOOT_HEAP_CACHE_BASE \
                                                    + RESERVED_FASTBOOT_HEAP_CACHE_SIZE)
#define RESERVED_FASTBOOT_HEAP_BASE RESERVED_FASTBOOT_HEAP_CACHE_TOP
#define RESERVED_FASTBOOT_HEAP_SIZE 0x1C00000
#define RESERVED_FASTBOOT_HEAP_TOP (RESERVED_FASTBOOT_HEAP_BASE \
                                                    + RESERVED_FASTBOOT_HEAP_SIZE)
#if (RESERVED_FASTBOOT_HEAP_TOP > (RESERVED_FASTBOOT_CMA_PHYMEM_BASE \
    + RESERVED_FASTBOOT_USED_PHYMEM_SIZE))
#error "fastboot memory overflow!!!"
#endif
#define RESERVED_FASTBOOT_AVB_HEAP_PHYMEM_BASE (RESERVED_DRM_CMA_BASE \
                                                     + RESERVED_BL2_VERIFY_BUFF_SIZE)
#define RESERVED_FASTBOOT_AVB_HEAP_PHYMEM_TOP (RESERVED_DRM_CMA_BASE \
                                                     + RESERVED_DRM_CMA_SIZE)
#define RESERVED_FASTBOOT_AVB_HEAP_PHYMEM_SIZE (RESERVED_FASTBOOT_AVB_HEAP_PHYMEM_TOP \
                                                     - RESERVED_FASTBOOT_AVB_HEAP_PHYMEM_BASE)
#define RESERVED_FASTBOOT_LHEAP_BASE RESERVED_KERNEL_DUMP_PROTECT_BASE
#define RESERVED_FASTBOOT_LHEAP_SIZE RESERVED_KERNEL_DUMP_PRORECT_SIZE
#define RESERVED_FASTBOOT_LHEAP_TOP (RESERVED_FASTBOOT_LHEAP_BASE \
                                                     + RESERVED_FASTBOOT_LHEAP_SIZE)
#ifdef CONFIG_HISI_GCOV_FASTBOOT
#define RESERVED_4G_DDR_FASTBOOT_GCDA_PHYMEM_BASE (0xC0000000)
#define RESERVED_6G_DDR_FASTBOOT_GCDA_PHYMEM_BASE (0x100000000ULL)
#define RESERVED_DDR_FASTBOOT_GCDA_PHYMEM_SIZE (0x200000)
#endif
#ifdef CONFIG_HISI_GCOV_SLT_HIBENCH
#define RESERVED_4G_DDR_SLT_HIBENCH_GCDA_PHYMEM_BASE (0xC0200000)
#define RESERVED_6G_DDR_SLT_HIBENCH_GCDA_PHYMEM_BASE (0x100200000ULL)
#define RESERVED_SLT_HIBENCH_GCDA_PHYMEM_SIZE (0x100000)
#endif
#endif
