#ifndef _HHEE_DDR_MAP_H_
#define _HHEE_DDR_MAP_H_ 
#include <global_ddr_map.h>
#define HHEE_RAM_BASE RESERVED_HHEE_PHYMEM_BASE
#define HHEE_RAM_TOTAL_SIZE RESERVED_HHEE_PHYMEM_SIZE
#define HHEE_IMAGE_SIZE 0x64000
#define HHEE_RAM_END (HHEE_RAM_BASE + HHEE_RAM_TOTAL_SIZE)
#define HHEE_KERNEL_PAGETBL_SIZE 0x10000
#define HHEE_KERNEL_PAGETBL_ADDR (HHEE_RAM_END - HHEE_KERNEL_PAGETBL_SIZE)
#define HHEE_MON_LOG_SIZE 0x0C000
#define HHEE_MON_LOG_ADDR (HHEE_KERNEL_PAGETBL_ADDR - HHEE_MON_LOG_SIZE)
#define HHEE_CRASH_LOG_SIZE 0x01000
#define HHEE_CRASH_LOG_ADDR (HHEE_MON_LOG_ADDR - HHEE_CRASH_LOG_SIZE)
#define HHEE_NORMAL_LOG_SIZE 0x0C000
#define HHEE_NORMAL_LOG_ADDR (HHEE_CRASH_LOG_ADDR - HHEE_NORMAL_LOG_SIZE)
#define HHEE_PMF_INFO_SIZE 0x06000
#define HHEE_PMF_INFO_ADDR (HHEE_NORMAL_LOG_ADDR - HHEE_PMF_INFO_SIZE)
#define HHEE_IRQ_INFO_SIZE 0x04000
#define HHEE_IRQ_INFO_ADDR (HHEE_PMF_INFO_ADDR - HHEE_IRQ_INFO_SIZE)
#define HHEE_BOOT_PARAM_SIZE 0x00400
#define HHEE_BOOT_PARAM_ADDR (HHEE_IRQ_INFO_ADDR - HHEE_BOOT_PARAM_SIZE)
#define HHEE_DDR_SEC_TABLE_SIZE 0x00400
#define HHEE_DDR_SEC_TABLE_ADDR (HHEE_BOOT_PARAM_ADDR - HHEE_DDR_SEC_TABLE_SIZE)
#define HHEE_DDR_HOLE_TABLE_SIZE 0x00800
#define HHEE_DDR_HOLE_TABLE_ADDR (HHEE_DDR_SEC_TABLE_ADDR - HHEE_DDR_HOLE_TABLE_SIZE)
#if defined(HHEE_CFG_GCOV_ENABLE) && HHEE_CFG_GCOV_ENABLE != 0
#define HHEE_GCOV_SIZE 0x100000
#define HHEE_GCOV_ADDR (HHEE_DDR_HOLE_TABLE_ADDR - HHEE_GCOV_SIZE)
#define HHEE_RAM_LIMIT HHEE_GCOV_ADDR
#else
#define HHEE_RAM_LIMIT HHEE_DDR_HOLE_TABLE_ADDR
#endif
#define HHEE_RAM_SIZE (HHEE_RAM_LIMIT - HHEE_RAM_BASE)
#endif
