#ifndef _LPNV_GLOBAL_H_
#define _LPNV_GLOBAL_H_ 
#define NVME_SIZE (104)
#define LPNV_LPNV "LPNV"
#define LPNV_LPMV "LPMV"
#define LPNV_LPDDR "LPDDR"
#define LPNV_THERMAL "THERMAL"
#define LPNV_PERIVOL "PERIVOL"
enum LPNV_FT_AP {
 LPNV_FT_AP_APNUM,
 LPNV_FT_AP_CPUMAP,
 LPNV_FT_AP_CPUIDLE,
 LPNV_FT_AP_AP_DVFS,
 LPNV_FT_AP_LIT_AVS,
 LPNV_FT_AP_MID_AVS,
 LPNV_FT_AP_BIG_AVS,
 LPNV_FT_AP_GPU_DVFS,
 LPNV_FT_AP_GPU_AVS,
 LPNV_FT_AP_TEMP_CTRL,
 LPNV_FT_AP_IPA,
 LPNV_FT_AP_LIT_SVFD,
 LPNV_FT_AP_MID_SVFD,
 LPNV_FT_AP_BIG_SVFD,
 LPNV_FT_AP_GPU_SVFD,
 LPNV_FT_AP_L3_DVFS,
 LPNV_FT_AP_L3_AVS,
 LPNV_FT_AP_L3_SVFD,
 LPNV_FT_AP_L3_PD,
 LPNV_FT_AP_L3_PSIZE,
 LPNV_FT_AP_SR,
 LPNV_FT_AP_L3_SHARE,
 LPNV_FT_AP_L3P_KARMA,
 LPNV_FT_AP_NPU_AVS,
 LPNV_FT_AP_NPU_SVFD,
 LPNV_FT_AP_MEMLAT,
 LPNV_FT_AP_MAX
};
enum LPNV_FT_MCU {
 LPNV_FT_MCU_DEEPSLEEP,
 LPNV_FT_MCU_SLEEP,
 LPNV_FT_MCU_HIFI_SR,
 LPNV_FT_MCU_HIFI_LOWPOWER,
 LPNV_FT_MCU_MMBUF_SR,
 LPNV_FT_MCU_PERIL_VOL,
 LPNV_FT_MCU_IOM_SR,
 LPNV_FT_MCU_AP_SR,
 LPNV_FT_MCU_BUS_DFS,
 LPNV_FT_MCU_DDR_AUTOGT_DMC_INT,
 LPNV_FT_MCU_DDR_AUTOGT_DMC_EXT,
 LPNV_FT_MCU_DDR_AUTOGT_DMSS_EXT,
 LPNV_FT_MCU_CPU_DDR_LINKAGE,
 LPNV_FT_MCU_GPU_DDR_LINKAGE,
 LPNV_FT_MCU_LOW_TEMP,
 LPNV_FT_MCU_GPU_IDLEDIV,
 LPNV_FT_MCU_PERI_AVS,
 LPNV_FT_MCU_KARMA,
 LPNV_FT_MCU_L3EXTENSION,
 LPNV_FT_MCU_AO_AVS,
 LPNV_FT_MCU_MAX
};
enum LPNV_FT_DDR {
 LPNV_FT_DDR_DFS,
 LPNV_FT_DDR_L1BUS_DFS,
 LPNV_FT_DDR_THERMAL,
 LPNV_FT_DDR_TMON_RECORD,
 LPNV_FT_DDR_TMON_RST,
 LPNV_FT_DDR_TMON_SHAKE_NRST,
 LPNV_FT_DDR_MAX
};
enum LPNV_FT_THERMAL {
 LPNV_FT_THERMAL_MCU_RESET,
 LPNV_FT_THERMAL_AP_RESET,
 LPNV_FT_THERMAL_DIE_THRESHOLD,
 LPNV_FT_THERMAL_HIGH_THRESHOLD,
 LPNV_FT_THERMAL_NOR_THRESHOLD,
 LPNV_FT_THERMAL_HOTPLUG,
 LPNV_FT_THERMAL_MAX
};
enum LPNV_FT_FREQVOL {
 LPNV_FT_FREQVOL_FREQ,
 LPNV_FT_FREQVOL_VOLT,
 LPNV_FT_FREQVOL_MEMVOLT,
 LPNV_FT_FREQVOL_LOWTEMP_VOLT_BIAS,
 LPNV_FT_FREQVOL_GPUMEM_VOLT,
 LPNV_FT_FREQVOL_MAX
};
enum LPNV_FT_GPU_FREQVOL {
 LPNV_FT_GPU_FREQVOL_FREQ,
 LPNV_FT_GPU_FREQVOL_VOLT,
 LPNV_FT_GPU_FREQVOL_FVOLT,
 LPNV_FT_GPU_FREQVOL_LOW_VOLT,
 LPNV_FT_GPU_FREQVOL_MAX
};
enum LPNV_FT_PERIVOL {
 LPNV_FT_PERIL_VOL_BIAS,
 LPNV_FT_PERIL_VOL_LOCK,
 LPNV_FT_PERIL_AVS_MODULE_SWI,
 LPNV_FT_PERIL_AO_BIAS,
 LPNV_FT_AO_VOL_LOCK,
 LPNV_FT_PERIL_VOL_MAX
};
enum LPNV_ITEM_MAP {
 LPNV_MAP_AP,
 LPNV_MAP_MCU,
 LPNV_MAP_DDR,
 LPNV_MAP_THERMAL,
 LPNV_LITTLE_FREQVOL,
 LPNV_MID_FREQVOL,
 LPNV_BIG_FREQVOL,
 LPNV_L3_FREQVOL,
 LPNV_GPU_FREQVOL,
 LPNV_PERIL_VOL,
 LPNV_ITEM_MAP_MAX
};
#endif
