#ifndef MSPE_DDR_REGION_H
#define MSPE_DDR_REGION_H 
#include <global_ddr_map.h>
#ifndef SIZE_1M
#define SIZE_1M (1 * 1024 * 1024)
#endif
#ifndef SIZE_512K
#define SIZE_512K (512 * 1024)
#endif
#ifndef SIZE_200K
#define SIZE_200K (200 * 1024)
#endif
#ifndef SIZE_100K
#define SIZE_100K (100 * 1024)
#endif
#ifndef SIZE_1K
#define SIZE_1K 1024
#endif
#ifndef SIZE_512
#define SIZE_512 512
#endif
#ifndef SIZE_128
#define SIZE_128 128
#endif
#ifndef SIZE_36
#define SIZE_36 36
#endif
#ifndef SIZE_4
#define SIZE_4 4
#endif
#define MSPE_DDR_REGION_BASE RESERVED_HIEPS_PHYMEM_BASE
#define MSPE_DDR_REGION_SIZE RESERVED_HIEPS_PHYMEM_SIZE
#define MSPE_DDR_REGION_SYMM_BASE MSPE_DDR_REGION_BASE
#define MSPE_DDR_REGION_SYMM_SIZE SIZE_1M
#define MSPE_DDR_REGION_SYMM_END (MSPE_DDR_REGION_SYMM_BASE + MSPE_DDR_REGION_SYMM_SIZE)
#define MSPE_DDR_REGION_HEAP_BASE MSPE_DDR_REGION_SYMM_END
#define MSPE_DDR_REGION_HEAP_SIZE SIZE_512K
#define MSPE_DDR_REGION_HEAP_END (MSPE_DDR_REGION_HEAP_BASE + MSPE_DDR_REGION_HEAP_SIZE)
#define MSPE_DDR_REGION_AUTOTEST_BASE MSPE_DDR_REGION_HEAP_END
#define MSPE_DDR_REGION_AUTOTEST_SIZE SIZE_200K
#define MSPE_DDR_REGION_AUTOTEST_END (MSPE_DDR_REGION_AUTOTEST_BASE + MSPE_DDR_REGION_AUTOTEST_SIZE)
#define MSPE_DDR_REGION_SHARE_BASE MSPE_DDR_REGION_AUTOTEST_END
#define MSPE_DDR_REGION_SHARE_SIZE SIZE_100K
#define MSPE_DDR_REGION_SHARE_END (MSPE_DDR_REGION_SHARE_BASE + MSPE_DDR_REGION_SHARE_SIZE)
#define MSPE_DDR_REGION_SMMU_BASE MSPE_DDR_REGION_SHARE_END
#define MSPE_DDR_REGION_SMMU_SIZE SIZE_1K
#define MSPE_DDR_REGION_SMMU_END (MSPE_DDR_REGION_SMMU_BASE + MSPE_DDR_REGION_SMMU_SIZE)
#define MSPE_DDR_REGION_IO_BASE MSPE_DDR_REGION_SHARE_BASE
#define MSPE_DDR_REGION_IO_SIZE (SIZE_512K - MSPE_DDR_REGION_AUTOTEST_SIZE)
#define MSPE_DDR_REGION_IO_END (MSPE_DDR_REGION_IO_BASE + MSPE_DDR_REGION_IO_SIZE)
#define MSPE_DDR_REGION_SMC_RET_FLAG_BASE MSPE_DDR_REGION_SHARE_BASE
#define MSPE_DDR_REGION_SMC_RET_FLAG_SIZE SIZE_4
#define MSPE_DDR_REGION_SMC_RET_FLAG_END (MSPE_DDR_REGION_SMC_RET_FLAG_BASE + MSPE_DDR_REGION_SMC_RET_FLAG_SIZE)
#define MSPE_DDR_REGION_SMC_POWER_RESULT_BASE MSPE_DDR_REGION_SMC_RET_FLAG_END
#define MSPE_DDR_REGION_SMC_POWER_RESULT_SIZE SIZE_4
#define MSPE_DDR_REGION_SMC_POWER_RESULT_END (MSPE_DDR_REGION_SMC_POWER_RESULT_BASE + MSPE_DDR_REGION_SMC_POWER_RESULT_SIZE)
#define MSPE_DDR_REGION_LCS_BASE MSPE_DDR_REGION_SMC_POWER_RESULT_END
#define MSPE_DDR_REGION_LCS_SIZE SIZE_4
#define MSPE_DDR_REGION_LCS_END (MSPE_DDR_REGION_LCS_BASE + MSPE_DDR_REGION_LCS_SIZE)
#define MSPE_DDR_REGION_KDR_BASE MSPE_DDR_REGION_LCS_END
#define MSPE_DDR_REGION_KDR_SIZE SIZE_36
#define MSPE_DDR_REGION_KDR_END (MSPE_DDR_REGION_KDR_BASE + MSPE_DDR_REGION_KDR_SIZE)
#define MSPE_DDR_REGION_SMMUV2_ERRADDR_BASE MSPE_DDR_REGION_SMMU_BASE
#define MSPE_DDR_REGION_SMMUV2_ERRADDR_SIZE SIZE_128
#define MSPE_DDR_REGION_SMMUV2_ERRADDR_END (MSPE_DDR_REGION_SMMUV2_ERRADDR_BASE + MSPE_DDR_REGION_SMMUV2_ERRADDR_SIZE)
#endif
