#ifndef __NPU_DDR_MAP_H__
#define __NPU_DDR_MAP_H__ 
#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif
#define RESERVED_NPU_AI_SERVER_PHYMEM_BASE 0x1BC00000
#define RESERVED_NPU_AI_SERVER_PHYMEM_SIZE 0xB00000
#define RESERVED_NPU_SEC_PHYMEM_BASE 0x1C700000
#define RESERVED_NPU_SEC_PHYMEM_SIZE 0x30000
#define NPU_NONSEC_RESERVED_DDR_BASE_ADDR (RESERVED_NPU_AI_SERVER_PHYMEM_BASE)
#define NPU_NONSEC_RESERVED_MEMORY_SIZE (RESERVED_NPU_AI_SERVER_PHYMEM_SIZE)
#define NPU_SEC_RESERVED_DDR_BASE_ADDR (RESERVED_NPU_SEC_PHYMEM_BASE)
#define NPU_SEC_RESERVED_DDR_SIZE (RESERVED_NPU_SEC_PHYMEM_SIZE)
#define NPU_NS_AICPU_FW_SIZE 0x100000
#define NPU_NS_TSCPU_FW_SIZE 0x400000
#define NPU_NS_SQCQ_SIZE 0x180000
#define NPU_NS_TASKPOOL_SIZE 0x100000
#define NPU_NS_LOG_SIZE 0x80000
#define NPU_NS_PROF_SIZE 0x100000
#define NPU_NS_BBOX_SIZE 0x40000
#define NPU_NS_DUMP_SIZE 0xC0000
#define NPU_NS_NPU_CONFIG_SIZE 0x1000
#define NPU_NS_AICPU_EL1_SIZE 0xFE000
#define NPU_NS_AICPU_CONFIG_SIZE 0x2000
#define NPU_NS_AICPU_RESERVED_SIZE 0
#define NPU_NS_TSCPU_EL1_SIZE 0x3FF000
#define NPU_NS_TSCPU_CONFIG_SIZE 0x1000
#define NPU_NS_TSCPU_RESERVED_SIZE 0x600000
#define NPU_NS_AICPU_FW_BASE_ADDR (NPU_NONSEC_RESERVED_DDR_BASE_ADDR)
#define NPU_NS_TSCPU_FW_BASE_ADDR (NPU_NS_AICPU_FW_BASE_ADDR + NPU_NS_AICPU_FW_SIZE)
#define NPU_NS_SQCQ_BUF_BASE_ADDR (NPU_NS_TSCPU_FW_BASE_ADDR + NPU_NS_TSCPU_FW_SIZE)
#define NPU_NS_TASKPOOL_BASE_ADDR (NPU_NS_SQCQ_BUF_BASE_ADDR + NPU_NS_SQCQ_SIZE)
#define NPU_NS_LOG_BASE_ADDR (NPU_NS_TASKPOOL_BASE_ADDR + NPU_NS_TASKPOOL_SIZE)
#define NPU_NS_PROFILE_BASE_ADDR (NPU_NS_LOG_BASE_ADDR + NPU_NS_LOG_SIZE)
#define NPU_NS_BBOX_BASE_ADDR (NPU_NS_PROFILE_BASE_ADDR + NPU_NS_PROF_SIZE)
#define NPU_NS_DATADUMP_BASE_ADDR (NPU_NS_BBOX_BASE_ADDR + NPU_NS_BBOX_SIZE)
#define NPU_NS_NPU_CONFIG_BASE_ADDR (NPU_NS_DATADUMP_BASE_ADDR + NPU_NS_DUMP_SIZE)
#define NPU_S_AICPU_EL3_SIZE 0
#define NPU_S_AICPU_RESERVED_SIZE 0
#define NPU_S_TSCPU_EL3_SIZE 0x1000
#define NPU_S_TSCPU_EL1_SIZE 0
#define NPU_S_NPU_CONFIG_SIZE 0x1000
#define NPU_S_AICPU_FW_SIZE (NPU_S_AICPU_EL3_SIZE + NPU_S_AICPU_RESERVED_SIZE)
#define NPU_S_TSCPU_FW_BK_SIZE 0x0
#define NPU_S_TSCPU_FW_SIZE (NPU_S_TSCPU_EL3_SIZE + NPU_S_TSCPU_EL1_SIZE)
#define NPU_S_CALC_SQ_AERA_SIZE 0
#define NPU_S_CALC_CQ_AERA_SIZE 0
#define NPU_S_TASKPOOL_SIZE 0
#define NPU_S_L2CTRL_CMA_SIZE 0
#define NPU_S_TS_LOG_SIZE 0
#define NPU_S_SMMU_QUEUE_SIZE 0
#define NPU_S_NPU_CONFIG_BASE_ADDR (NPU_SEC_RESERVED_DDR_BASE_ADDR)
#define NPU_S_AICPU_FW_BASE_ADDR (NPU_S_NPU_CONFIG_BASE_ADDR + NPU_S_NPU_CONFIG_SIZE)
#define NPU_S_TSCPU_FW_BK_BASE_ADDR (NPU_S_AICPU_FW_BASE_ADDR + NPU_S_AICPU_FW_SIZE)
#define NPU_S_TSCPU_FW_BASE_ADDR (NPU_S_TSCPU_FW_BK_BASE_ADDR + NPU_S_TSCPU_FW_BK_SIZE)
#define NPU_S_CALC_SQ_AERA_BASE_ADDR (NPU_S_TSCPU_FW_BASE_ADDR + NPU_S_TSCPU_FW_SIZE)
#define NPU_S_CALC_CQ_AERA_BASE_ADDR (NPU_S_CALC_SQ_AERA_BASE_ADDR + NPU_S_CALC_SQ_AERA_SIZE)
#define NPU_S_TASKPOOL_BASE_ADDR (NPU_S_CALC_CQ_AERA_BASE_ADDR + NPU_S_CALC_CQ_AERA_SIZE)
#define NPU_S_L2CTRL_CMA_BASE_ADDR (NPU_S_TASKPOOL_BASE_ADDR + NPU_S_TASKPOOL_SIZE)
#define NPU_S_TS_LOG_BASE_ADDR (NPU_S_L2CTRL_CMA_BASE_ADDR + NPU_S_L2CTRL_CMA_SIZE)
#define NPU_S_SMMU_QUEUE_BASE_ADDR (NPU_S_TS_LOG_BASE_ADDR + NPU_S_TS_LOG_SIZE)
#define NPU_S_AICPU_FW_EL3_ADDR (NPU_S_AICPU_FW_BASE_ADDR)
#define NPU_S_TSCPU_FW_EL3_ADDR (NPU_S_TSCPU_FW_BASE_ADDR)
#define NPU_S_TSCPU_FW_EL1_ADDR (NPU_S_TSCPU_FW_EL3_ADDR + NPU_S_TSCPU_EL3_SIZE)
#define NPU_TASK_POOL_RESMEM_ADDR NPU_NS_TASKPOOL_BASE_ADDR
#define NPU_LOG_RESMEM_ADDR NPU_NS_LOG_BASE_ADDR
#define NPU_SQCQ_RESMEM_ADDR NPU_NS_SQCQ_BUF_BASE_ADDR
#define NPU_SQCQ_RESMEM_SIZE NPU_NS_SQCQ_SIZE
#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif
