#ifndef _SECS_PLATFORM_DEF_H_
#define _SECS_PLATFORM_DEF_H_ 
#include "soc_lpmcu_baseaddr_interface.h"
#include "soc_acpu_baseaddr_interface.h"
#include "m3_sram_map.h"
#define LPRAM_SIZE 0x58000
#define DRAM_SIZE 0x10000000
#define SECRAM_SIZE 0x40000
#define IOMCU_SIZE 0x000f0000
#define TWO_LEVEL_SECDBG_IMAGE_SIZE 1396
#define THREE_LEVEL_SECDBG_IMAGE_SIZE 0x840
#define THREE_LEVEL_CERT_MAXSIZE (4 * 1024)
#ifdef CC_CONFIG_USE_SECRAM
 #define REG_BASE_SECRAM (SOC_LPMCU_SECRAM_remap_BASE_ADDR)
 #define SECRAM_ACPU_BASE (SOC_ACPU_SECRAM_BASE_ADDR)
#endif
#ifdef CC_CONFIG_USE_IOMCU
 #define REG_BASE_IOMCU SOC_LPMCU_IOMCU_DTCM_BASE_ADDR
 #define IOMCU_ACPU_BASE SOC_ACPU_IOMCU_DTCM_BASE_ADDR
#endif
#ifdef CC_USE_IN_XLOADER
 #define REG_BASE_SECENG_S (SOC_LPMCU_CCS_BASE_ADDR)
 #define REG_BASE_LP_RAM (SOC_LPMCU_LP_RAM_BASE_ADDR)
 #define LPRAM_BASE (SOC_ACPU_LP_RAM_BASE_ADDR)
 #define REG_BASE_DRAM_ADDR (SOC_LPMCU_DRAM_BASE_ADDR)
 #define REG_BASE_LPM3_CONFIG (SOC_LPMCU_LP_CONFIG_BASE_ADDR)
 #define SECENGS_BASE_ADDR (REG_BASE_SECENG_S)
#else
 #define SECENGS_BASE_ADDR (SOC_ACPU_CCS_BASE_ADDR)
#endif
#ifdef CC_CONFIG_USE_UCE
 #define REG_BASE_UCE_ADDR (SOC_LPMCU_DMCPACK0_BASE_ADDR + 0x8000)
 #define UCE_ACPU_BASE (SOC_ACPU_DMCPACK0_BASE_ADDR + 0x8000)
#endif
#define OTP_HASH_GROUP_SIZE 4
#define OTP_HASH_VERIFICATION_GROUP 66
#define OTP_HASH_VERIFICATION_MASK 0x80000
#endif
