#ifndef __BIU_REG_OFFSET_H__
#define __BIU_REG_OFFSET_H__ 
#define SOC_BIU_BASE (0x0)
#define SOC_BIU_BIU_STATUS2_REG (SOC_BIU_BASE + 0xD28)
#define SOC_BIU_BIU_STATUS3_REG (SOC_BIU_BASE + 0xD30)
#define SOC_BIU_BIU_STATUS4_REG (SOC_BIU_BASE + 0xD38)
#define SOC_BIU_L2_REMAP_PADDR_BASE_REG (SOC_BIU_BASE + 0xD50)
#define SOC_BIU_L2_PAGE_SIZE_REG (SOC_BIU_BASE + 0xD58)
#define SOC_BIU_L2_SIZE_REG (SOC_BIU_BASE + 0xD60)
#define SOC_BIU_BIU_CTRL3_REG (SOC_BIU_BASE + 0xD80)
#define SOC_BIU_BIU_CTRL4_REG (SOC_BIU_BASE + 0xD88)
#define SOC_BIU_BIU_CTRL5_REG (SOC_BIU_BASE + 0xD90)
#define SOC_BIU_BIU_STATUS6_REG (SOC_BIU_BASE + 0xD98)
#define SOC_BIU_BIU_STATUS7_REG (SOC_BIU_BASE + 0xDA0)
#endif
