#ifndef __NPU_HW_EXP_IRQ_REG_OFFSET_H__
#define __NPU_HW_EXP_IRQ_REG_OFFSET_H__ 
#define SOC_NPU_HW_EXP_IRQ_BASE (0xE5E06000)
#define SOC_NPU_HW_EXP_IRQ_NPU_HW_EXP_IRQ_SET_REG (SOC_NPU_HW_EXP_IRQ_BASE + 0x0)
#define SOC_NPU_HW_EXP_IRQ_NPU_HW_EXP_IRQ_CLR_REG (SOC_NPU_HW_EXP_IRQ_BASE + 0x4)
#define SOC_NPU_HW_EXP_IRQ_NPU_HW_EXP_IRQ_STAT_REG (SOC_NPU_HW_EXP_IRQ_BASE + 0x8)
#define SOC_NPU_HW_EXP_IRQ_NPU_HW_EXP_IRQ_SET_P_REG (SOC_NPU_HW_EXP_IRQ_BASE + 0xC)
#define SOC_NPU_HW_EXP_IRQ_NPU_HW_EXP_IRQ_CFG_REG (SOC_NPU_HW_EXP_IRQ_BASE + 0x100)
#endif
