#ifndef __TSCPU_A55_CFG_REG_OFFSET_H__
#define __TSCPU_A55_CFG_REG_OFFSET_H__ 
#define SOC_TSCPU_A55_CFG_BASE (0xe4021000)
#define SOC_TSCPU_A55_CFG_ANANKE_DBG_CLR_CFG_REG_REG (SOC_TSCPU_A55_CFG_BASE + 0x874)
#define SOC_TSCPU_A55_CFG_ANANKE_DBG_PC_LO_REG (SOC_TSCPU_A55_CFG_BASE + 0xC80)
#define SOC_TSCPU_A55_CFG_ANANKE_DBG_PC_HI_REG (SOC_TSCPU_A55_CFG_BASE + 0xC84)
#define SOC_TSCPU_A55_CFG_ANANKE_DBG_SP_LO_REG (SOC_TSCPU_A55_CFG_BASE + 0xC88)
#define SOC_TSCPU_A55_CFG_ANANKE_DBG_SP_HI_REG (SOC_TSCPU_A55_CFG_BASE + 0xC8C)
#endif
