#ifndef __DB_REG_REG_OFFSET_H__
#define __DB_REG_REG_OFFSET_H__ 
#define SOC_DB_REG_BASE (0x0)
#define SOC_DB_REG_DB_INT_SUMMARY_REG (SOC_DB_REG_BASE + 0x10)
#define SOC_DB_REG_DB_INT_MASK0_REG (SOC_DB_REG_BASE + 0x20)
#define SOC_DB_REG_DB_INT_MASK1_REG (SOC_DB_REG_BASE + 0x24)
#define SOC_DB_REG_DB_INT_MASK2_REG (SOC_DB_REG_BASE + 0x28)
#define SOC_DB_REG_DB_INT_MASK3_REG (SOC_DB_REG_BASE + 0x2C)
#define SOC_DB_REG_DB_INT_STATUS0_REG (SOC_DB_REG_BASE + 0xA0)
#define SOC_DB_REG_DB_INT_STATUS1_REG (SOC_DB_REG_BASE + 0xA4)
#define SOC_DB_REG_DB_INT_STATUS2_REG (SOC_DB_REG_BASE + 0xA8)
#define SOC_DB_REG_DB_INT_STATUS3_REG (SOC_DB_REG_BASE + 0xAC)
#define SOC_DB_REG_DB_SEC_CTRL_REG (SOC_DB_REG_BASE + 0x200)
#endif
