#ifndef __SOC_EFUSE_INTERFACE_H__
#define __SOC_EFUSE_INTERFACE_H__ 
#ifdef __cplusplus
    #if __cplusplus
        extern "C" {
    #endif
#endif
#define EFUSE_ATTR_READABLE (0x00000001UL)
#define EFUSE_ATTR_READ_DEVICE (0x00000002UL)
#define EFUSE_ATTR_READ_SRAM (0x00000004UL)
#define EFUSE_ATTR_READ_ZERO (0x00000008UL)
#define EFUSE_ATTR_WRITEABLE (0x00000100UL)
#define EFUSE_ATTR_WRITE_NOT_UPDATE (0x00000200UL)
#define EFUSE_ATTR_WRITE_CHECK (0x00000400UL)
typedef struct {
 unsigned int start_bit;
 unsigned int bit_cnt;
 unsigned int id;
 unsigned int attr;
} efuse_attr_t;
#if defined(CONFIG_EFUSE_IN_XLOADER)
enum {
 EFUSE_GPU_VDDPC = 0,
 EFUSE_DIEID_VALUE,
 EFUSE_IDDQ_VALUE,
 EFUSE_GENERALSEE_EFUSE4,
 EFUSE_HPM_TRIM,
 EFUSE_MEMORYREPAIR_BYPN,
 EFUSE_ONLINE_REPAIR,
 EFUSE_OTP_SEVD_ENABLE,
 EFUSE_REMOTE_TSENSOR,
 EFUSE_TENSOR_TRIM,
 EFUSE_HBK0_VALUE = 10,
 EFUSE_HBK1_VALUE,
 EFUSE_SECDBG_CTRL,
 EFUSE_PARTIALGOOD_FLAG,
 EFUSE_DMHASH_VALUE,
 EFUSE_SOFT_COUNTER,
 EFUSE_MODEM_PASENSOR,
 EFUSE_MODEM_AVSFT,
 EFUSE_MODEM_IPY,
 EFUSE_PARTIALGOOD_AUTOFLAG,
 EFUSE_SLT_B25 = 20,
};
#elif defined(CONFIG_EFUSE_IN_BL2)
enum {
 EFUSE_HUK_VALUE = 0,
 EFUSE_SCP_VALUE,
 EFUSE_MP_FLAG,
 EFUSE_HUK_ZEROES,
 EFUSE_SCP_ZEROES,
 EFUSE_OEMP_FLAG,
 EFUSE_HBK1_ZEROES,
 EFUSE_KCE_ZEROES,
 EFUSE_KCE_VALUE,
 EFUSE_HBK0_VALUE,
 EFUSE_HBK1_VALUE = 10,
 EFUSE_TRB_COUNTER,
 EFUSE_NTRB_COUNTER,
 EFUSE_EKCST_VALUE,
 EFUSE_EKCST_ZEROES,
 EFUSE_DIEID_VALUE,
 EFUSE_SLT_FINISH,
 EFUSE_SOFT_COUNTER,
 EFUSE_MODEM_HUK,
 EFUSE_MODEM_HUKZEROES,
 EFUSE_DMHASH_VALUE = 20,
 EFUSE_FLASH_COUNT,
 EFUSE_PARTIALGOOD_FLAG,
 EFUSE_CC712_KPTRL,
 EFUSE_CHIP_ID,
 EFUSE_DJTAG_CTRL,
 EFUSE_MODEM_DBGBYPASS,
 EFUSE_PAD_DISABLE,
 EFUSE_HUKRD_DISABLE,
 EFUSE_SCPRD_DISABLE,
 EFUSE_SECDBG_CTRL = 30,
 EFUSE_SECDBG_DBGEN,
 EFUSE_SECDBG_NIDEN,
 EFUSE_SECDBG_SPIDEN,
 EFUSE_SECDBG_SPNIDEN,
 EFUSE_SECDBG_DSPJTAGDIS,
 EFUSE_SECENG_EKCSTRDEN,
 EFUSE_KPRTLRD_DISABLE,
 EFUSE_DX_CLKEN,
 EFUSE_DICE_EN,
 EFUSE_DCIE_SECENGINE = 40,
 EFUSE_GPU_VDDPC,
 EFUSE_IDDQ_VALUE,
 EFUSE_GENERALSEE_EFUSE4,
 EFUSE_HPM_TRIM,
 EFUSE_TENSOR_TRIM,
 EFUSE_MEMORYREPAIR_BYPN,
 EFUSE_ONLINE_REPAIR,
 EFUSE_GENERALSE_FLAG,
 EFUSE_OTP_SEVD_ENABLE,
 EFUSE_CHIPID_VLD = 50,
 EFUSE_DFTKEY_ZEROES,
 EFUSE_GENERALSEE_EFUSE1,
 EFUSE_GENERALSEE_EFUSE2,
 EFUSE_GENERALSEE_EFUSE3,
 EFUSE_DJTAGAUTH_KEY,
 EFUSE_DJTAGKEY_ZEROES,
 EFUSE_DJTAGRW_DISABLE,
 EFUSE_KCST_DIS,
 EFUSE_SEC_DIS,
 EFUSE_UDS_VALUE = 60,
 EFUSE_REMOTE_TSENSOR,
 EFUSE_CDPHY_OFFSETCALIB,
 EFUSE_CPHY_BIAS,
 EFUSE_CORNER_CSI,
 EFUSE_SS_CORNER,
 EFUSE_PASENSOR_A53GPU,
 EFUSE_PASENSOR_A73,
#if defined(CONFIG_DEBUG_EFUSE)
 EFUSE_DEBUG_ID,
#endif
};
#elif defined(CONFIG_EFUSE_IN_BL31)
enum {
 EFUSE_HUK_VALUE = 0,
 EFUSE_SCP_VALUE,
 EFUSE_MP_FLAG,
 EFUSE_HUK_ZEROES,
 EFUSE_SCP_ZEROES,
 EFUSE_OEMP_FLAG,
 EFUSE_HBK1_ZEROES,
 EFUSE_KCE_ZEROES,
 EFUSE_KCE_VALUE,
 EFUSE_HBK0_VALUE,
 EFUSE_HBK1_VALUE = 10,
 EFUSE_TRB_COUNTER,
 EFUSE_NTRB_COUNTER,
 EFUSE_EKCST_VALUE,
 EFUSE_EKCST_ZEROES,
 EFUSE_DIEID_VALUE,
 EFUSE_SLT_FINISH,
 EFUSE_SOFT_COUNTER,
 EFUSE_MODEM_HUK,
 EFUSE_MODEM_HUKZEROES,
 EFUSE_DMHASH_VALUE = 20,
 EFUSE_FLASH_COUNT,
 EFUSE_PARTIALGOOD_FLAG,
 EFUSE_CC712_KPTRL,
 EFUSE_CHIP_ID,
 EFUSE_DJTAG_CTRL,
 EFUSE_MODEM_DBGBYPASS,
 EFUSE_PAD_DISABLE,
 EFUSE_HUKRD_DISABLE,
 EFUSE_SCPRD_DISABLE,
 EFUSE_SECDBG_CTRL = 30,
 EFUSE_SECDBG_DBGEN,
 EFUSE_SECDBG_NIDEN,
 EFUSE_SECDBG_SPIDEN,
 EFUSE_SECDBG_SPNIDEN,
 EFUSE_SECDBG_DSPJTAGDIS,
 EFUSE_SECENG_EKCSTRDEN,
 EFUSE_KPRTLRD_DISABLE,
 EFUSE_DX_CLKEN,
 EFUSE_DICE_EN,
 EFUSE_DCIE_SECENGINE = 40,
 EFUSE_GPU_VDDPC,
 EFUSE_IDDQ_VALUE,
 EFUSE_GENERALSEE_EFUSE4,
 EFUSE_HPM_TRIM,
 EFUSE_TENSOR_TRIM,
 EFUSE_MEMORYREPAIR_BYPN,
 EFUSE_ONLINE_REPAIR,
 EFUSE_GENERALSE_FLAG,
 EFUSE_OTP_SEVD_ENABLE,
 EFUSE_CHIPID_VLD = 50,
 EFUSE_DFTKEY_ZEROES,
 EFUSE_GENERALSEE_EFUSE1,
 EFUSE_GENERALSEE_EFUSE2,
 EFUSE_GENERALSEE_EFUSE3,
 EFUSE_DJTAGAUTH_KEY,
 EFUSE_DJTAGKEY_ZEROES,
 EFUSE_DJTAGRW_DISABLE,
 EFUSE_KCST_DIS,
 EFUSE_SEC_DIS,
 EFUSE_UDS_VALUE = 60,
 EFUSE_REMOTE_TSENSOR,
 EFUSE_ROM_USB,
 EFUSE_BURGLAR_PROOF,
 EFUSE_CDPHY_OFFSETCALIB,
 EFUSE_CPHY_BIAS,
 EFUSE_CORNER_CSI,
 EFUSE_SS_CORNER,
 EFUSE_PASENSOR_A53GPU,
 EFUSE_PASENSOR_A73,
 EFUSE_MODEM_PASENSOR = 70,
 EFUSE_MODEM_AVSFT,
 EFUSE_MODEM_IPY,
 EFUSE_PARTIALGOOD_AUTOFLAG,
};
#elif defined(CONFIG_EFUSE_IN_HIBENCH)
enum {
 EFUSE_HUK_VALUE = 0,
 EFUSE_SCP_VALUE,
 EFUSE_MP_FLAG,
 EFUSE_HUK_ZEROES,
 EFUSE_SCP_ZEROES,
 EFUSE_OEMP_FLAG,
 EFUSE_HBK1_ZEROES,
 EFUSE_KCE_ZEROES,
 EFUSE_KCE_VALUE,
 EFUSE_HBK0_VALUE,
 EFUSE_HBK1_VALUE = 10,
 EFUSE_TRB_COUNTER,
 EFUSE_NTRB_COUNTER,
 EFUSE_EKCST_VALUE,
 EFUSE_EKCST_ZEROES,
 EFUSE_DIEID_VALUE,
 EFUSE_SLT_FINISH,
 EFUSE_SOFT_COUNTER,
 EFUSE_MODEM_HUK,
 EFUSE_MODEM_HUKZEROES,
 EFUSE_DMHASH_VALUE = 20,
 EFUSE_FLASH_COUNT,
 EFUSE_PARTIALGOOD_FLAG,
 EFUSE_CC712_KPTRL,
 EFUSE_CHIP_ID,
 EFUSE_DJTAG_CTRL,
 EFUSE_MODEM_DBGBYPASS,
 EFUSE_PAD_DISABLE,
 EFUSE_HUKRD_DISABLE,
 EFUSE_SCPRD_DISABLE,
 EFUSE_SECDBG_CTRL = 30,
 EFUSE_SECDBG_DBGEN,
 EFUSE_SECDBG_NIDEN,
 EFUSE_SECDBG_SPIDEN,
 EFUSE_SECDBG_SPNIDEN,
 EFUSE_SECDBG_DSPJTAGDIS,
 EFUSE_SECENG_EKCSTRDEN,
 EFUSE_KPRTLRD_DISABLE,
 EFUSE_DX_CLKEN,
 EFUSE_DICE_EN,
 EFUSE_DCIE_SECENGINE = 40,
 EFUSE_GPU_VDDPC,
 EFUSE_IDDQ_VALUE,
 EFUSE_GENERALSEE_EFUSE4,
 EFUSE_HPM_TRIM,
 EFUSE_TENSOR_TRIM,
 EFUSE_MEMORYREPAIR_BYPN,
 EFUSE_ONLINE_REPAIR,
 EFUSE_GENERALSE_FLAG,
 EFUSE_OTP_SEVD_ENABLE,
 EFUSE_CHIPID_VLD = 50,
 EFUSE_DFTKEY_ZEROES,
 EFUSE_GENERALSEE_EFUSE1,
 EFUSE_GENERALSEE_EFUSE2,
 EFUSE_GENERALSEE_EFUSE3,
 EFUSE_DJTAGAUTH_KEY,
 EFUSE_DJTAGKEY_ZEROES,
 EFUSE_DJTAGRW_DISABLE,
 EFUSE_KCST_DIS,
 EFUSE_SEC_DIS,
 EFUSE_UDS_VALUE = 60,
 EFUSE_REMOTE_TSENSOR,
 EFUSE_SVFD_VMIN,
 EFUSE_CDPHY_OFFSETCALIB,
 EFUSE_CPHY_BIAS,
 EFUSE_CORNER_CSI,
 EFUSE_SS_CORNER,
 EFUSE_PASENSOR_A53GPU,
 EFUSE_MODEM_PASENSOR,
 EFUSE_MODEM_AVSFT,
 EFUSE_MODEM_IPY = 70,
 EFUSE_PARTIALGOOD_AUTOFLAG,
};
#endif
#define EFUSE_HUK_VALUE_START 0
#define EFUSE_HUK_VALUE_SIZE 256
#define EFUSE_SCP_VALUE_START 256
#define EFUSE_SCP_VALUE_SIZE 64
#define EFUSE_MP_FLAG_START 320
#define EFUSE_MP_FLAG_SIZE 32
#define EFUSE_HUK_ZEROES_START 320
#define EFUSE_HUK_ZEROES_SIZE 8
#define EFUSE_SCP_ZEROES_START 328
#define EFUSE_SCP_ZEROES_SIZE 7
#define EFUSE_KCST_DIS_START 335
#define EFUSE_KCST_DIS_SIZE 1
#define EFUSE_SEC_DIS_START 336
#define EFUSE_SEC_DIS_SIZE 4
#define EFUSE_OEMP_FLAG_START 352
#define EFUSE_OEMP_FLAG_SIZE 32
#define EFUSE_HBK1_ZEROES_START 360
#define EFUSE_HBK1_ZEROES_SIZE 8
#define EFUSE_KCE_ZEROES_START 376
#define EFUSE_KCE_ZEROES_SIZE 8
#define EFUSE_KCE_VALUE_START 384
#define EFUSE_KCE_VALUE_SIZE 128
#define EFUSE_HBK0_VALUE_START 512
#define EFUSE_HBK0_VALUE_SIZE 128
#define EFUSE_HBK1_VALUE_START 640
#define EFUSE_HBK1_VALUE_SIZE 128
#define EFUSE_TRB_COUNTER_START 768
#define EFUSE_TRB_COUNTER_SIZE 32
#define EFUSE_NTRB_COUNTER_START 800
#define EFUSE_NTRB_COUNTER_SIZE 224
#define EFUSE_EKCST_VALUE_START 1024
#define EFUSE_EKCST_VALUE_SIZE 128
#define EFUSE_EKCST_ZEROES_START 1152
#define EFUSE_EKCST_ZEROES_SIZE 32
#define EFUSE_DIEID_VALUE_START 1184
#define EFUSE_DIEID_VALUE_SIZE 160
#define EFUSE_IDDQ_VALUE_START 1344
#define EFUSE_IDDQ_VALUE_SIZE 50
#define EFUSE_TENSOR_TRIM_START 1394
#define EFUSE_TENSOR_TRIM_SIZE 55
#define EFUSE_HPM_TRIM_START 1449
#define EFUSE_HPM_TRIM_SIZE 10
#define EFUSE_REMOTE_TSENSOR_START 1459
#define EFUSE_REMOTE_TSENSOR_SIZE 162
#define EFUSE_PASENSOR_A73_START 1621
#define EFUSE_PASENSOR_A73_SIZE 10
#define EFUSE_SVFD_VMIN_START 1631
#define EFUSE_SVFD_VMIN_SIZE 201
#define EFUSE_PASENSOR_A53GPU_START 1832
#define EFUSE_PASENSOR_A53GPU_SIZE 20
#define EFUSE_GPU_VDDPC_START 1860
#define EFUSE_GPU_VDDPC_SIZE 2
#define EFUSE_MODEM_PASENSOR_START 1934
#define EFUSE_MODEM_PASENSOR_SIZE 10
#define EFUSE_MODEM_AVSFT_START 1944
#define EFUSE_MODEM_AVSFT_SIZE 9
#define EFUSE_MODEM_IPY_START 1953
#define EFUSE_MODEM_IPY_SIZE 7
#define EFUSE_SLT_FINISH_START 1960
#define EFUSE_SLT_FINISH_SIZE 3
#define EFUSE_SOFT_COUNTER_START 1963
#define EFUSE_SOFT_COUNTER_SIZE 32
#define EFUSE_MODEM_HUK_START 1995
#define EFUSE_MODEM_HUK_SIZE 128
#define EFUSE_MODEM_HUKZEROES_START 2123
#define EFUSE_MODEM_HUKZEROES_SIZE 8
#define EFUSE_DMHASH_VALUE_START 2131
#define EFUSE_DMHASH_VALUE_SIZE 1
#define EFUSE_FLASH_COUNT_START 2132
#define EFUSE_FLASH_COUNT_SIZE 8
#define EFUSE_BURGLAR_PROOF_START 2140
#define EFUSE_BURGLAR_PROOF_SIZE 1
#define EFUSE_ONLINE_REPAIR_START 2141
#define EFUSE_ONLINE_REPAIR_SIZE 3
#define EFUSE_CDPHY_OFFSETCALIB_START 2144
#define EFUSE_CDPHY_OFFSETCALIB_SIZE 220
#define EFUSE_CPHY_BIAS_START 2364
#define EFUSE_CPHY_BIAS_SIZE 36
#define EFUSE_CORNER_CSI_START 2400
#define EFUSE_CORNER_CSI_SIZE 36
#define EFUSE_SS_CORNER_START 2436
#define EFUSE_SS_CORNER_SIZE 1
#define EFUSE_SLT_B25_START 2454
#define EFUSE_SLT_B25_SIZE 2
#define EFUSE_UDS_VALUE_START 2464
#define EFUSE_UDS_VALUE_SIZE 256
#define EFUSE_DICE_EN_START 3120
#define EFUSE_DICE_EN_SIZE 2
#define EFUSE_DCIE_SECENGINE_START 3124
#define EFUSE_DCIE_SECENGINE_SIZE 1
#define EFUSE_ROM_USB_START 3126
#define EFUSE_ROM_USB_SIZE 3
#define EFUSE_OTP_SEVD_ENABLE_START 3129
#define EFUSE_OTP_SEVD_ENABLE_SIZE 1
#define EFUSE_GENERALSE_FLAG_START 3130
#define EFUSE_GENERALSE_FLAG_SIZE 2
#define EFUSE_PARTIALGOOD_FLAG_START 3132
#define EFUSE_PARTIALGOOD_FLAG_SIZE 292
#define EFUSE_PARTIALGOOD_AUTOFLAG_START 3424
#define EFUSE_PARTIALGOOD_AUTOFLAG_SIZE 128
#define EFUSE_DJTAGAUTH_KEY_START 3552
#define EFUSE_DJTAGAUTH_KEY_SIZE 64
#define EFUSE_CC712_KPTRL_START 3680
#define EFUSE_CC712_KPTRL_SIZE 128
#define EFUSE_CHIP_ID_START 3872
#define EFUSE_CHIP_ID_SIZE 64
#define EFUSE_DFTKEY_ZEROES_START 3992
#define EFUSE_DFTKEY_ZEROES_SIZE 8
#define EFUSE_GENERALSEE_EFUSE1_START 4000
#define EFUSE_GENERALSEE_EFUSE1_SIZE 32
#define EFUSE_CHIPID_VLD_START 4032
#define EFUSE_CHIPID_VLD_SIZE 1
#define EFUSE_MEMORYREPAIR_BYPN_START 4035
#define EFUSE_MEMORYREPAIR_BYPN_SIZE 1
#define EFUSE_GENERALSEE_EFUSE2_START 4036
#define EFUSE_GENERALSEE_EFUSE2_SIZE 9
#define EFUSE_GENERALSEE_EFUSE3_START 4046
#define EFUSE_GENERALSEE_EFUSE3_SIZE 2
#define EFUSE_DJTAG_CTRL_START 4050
#define EFUSE_DJTAG_CTRL_SIZE 2
#define EFUSE_DJTAGKEY_ZEROES_START 4053
#define EFUSE_DJTAGKEY_ZEROES_SIZE 8
#define EFUSE_MODEM_DBGBYPASS_START 4061
#define EFUSE_MODEM_DBGBYPASS_SIZE 1
#define EFUSE_PAD_DISABLE_START 4065
#define EFUSE_PAD_DISABLE_SIZE 1
#define EFUSE_GENERALSEE_EFUSE4_START 4068
#define EFUSE_GENERALSEE_EFUSE4_SIZE 2
#define EFUSE_HUKRD_DISABLE_START 4070
#define EFUSE_HUKRD_DISABLE_SIZE 1
#define EFUSE_SCPRD_DISABLE_START 4071
#define EFUSE_SCPRD_DISABLE_SIZE 1
#define EFUSE_SECDBG_CTRL_START 4073
#define EFUSE_SECDBG_CTRL_SIZE 2
#define EFUSE_SECDBG_DBGEN_START 4075
#define EFUSE_SECDBG_DBGEN_SIZE 1
#define EFUSE_SECDBG_NIDEN_START 4076
#define EFUSE_SECDBG_NIDEN_SIZE 1
#define EFUSE_SECDBG_SPIDEN_START 4077
#define EFUSE_SECDBG_SPIDEN_SIZE 1
#define EFUSE_SECDBG_SPNIDEN_START 4078
#define EFUSE_SECDBG_SPNIDEN_SIZE 1
#define EFUSE_SECDBG_DSPJTAGDIS_START 4079
#define EFUSE_SECDBG_DSPJTAGDIS_SIZE 1
#define EFUSE_SECENG_EKCSTRDEN_START 4083
#define EFUSE_SECENG_EKCSTRDEN_SIZE 1
#define EFUSE_KPRTLRD_DISABLE_START 4084
#define EFUSE_KPRTLRD_DISABLE_SIZE 1
#define EFUSE_DJTAGRW_DISABLE_START 4087
#define EFUSE_DJTAGRW_DISABLE_SIZE 1
#define EFUSE_DX_CLKEN_START 4092
#define EFUSE_DX_CLKEN_SIZE 1
#define EFUSE_MAX_SIZE 4096
#define EFUSE_ITEM_MAX 292
#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif
#endif
