#ifndef __SOC_MID_H__
#define __SOC_MID_H__ 
#define SOC_LPMCU_MID 0x0
#define SOC_IOMCU_M7_MID 0x1
#define SOC_PERF_STAT_MID 0x3
#define SOC_IPF_MID 0x4
#define SOC_DJTAG_M_MID 0x5
#define SOC_IOMCU_DMA_MID 0x6
#define SOC_UFS_MID 0x7
#define SOC_SD_MID 0x8
#define SOC_SDIO_MID 0x9
#define SOC_CC712_MID 0xa
#define SOC_HSDT_TCU_MID 0xb
#define SOC_DPC_MID 0xc
#define SOC_SOCP_MID 0xd
#define SOC_USB31OTG_MID 0xe
#define SOC_MODEM_EICC_AP_MID 0xf
#define SOC_DMAC_MID 0x10
#define SOC_ASP_HIFI_MID 0x11
#define SOC_PCIE_0_MID 0x12
#define SOC_ATGS_MID 0x13
#define SOC_ASP_DMA_USB_HDMI_MID 0x14
#define SOC_MODEM_MAA_AP_MID 0x15
#define SOC_MODEM_SPE_AP_MID 0x24
#define SOC_MODEM_TSP_CORE_THREAD0_MID 0x2d
#define SOC_MODEM_TSP_CORE_THREAD1_MID 0x2e
#define SOC_MODEM_TSP_CORE_THREAD2_MID 0x2f
#define SOC_MODEM_TSP_CORE_THREAD3_MID 0x30
#define SOC_MODEM_TSP_CORE_THREAD4_MID 0x31
#define SOC_MODEM_TSP_CORE_THREAD5_MID 0x32
#define SOC_MODEM_TSP_CORE_THREAD6_MID 0x33
#define SOC_MODEM_TSP_CORE_THREAD7_MID 0x34
#define SOC_MODEM_TSP_CORE_PCC_MID 0x35
#define SOC_MODEM_MDM_RRT_MID 0x26
#define SOC_MODEM_MDM_CIPHER5G_MID 0x27
#define SOC_MODEM_MDM_LATMON_MID 0x28
#define SOC_MODEM_MDM_L2DLE_MID 0x29
#define SOC_MODEM_MDM_EICC0_MID 0x2a
#define SOC_MODEM_MDM_EDMA0_MID 0x2b
#define SOC_MODEM_MDM_EDMA1_MID 0x2c
#define SOC_MODEM_MDM_CICOM0_MID 0x16
#define SOC_MODEM_MDM_UPACC_MID 0x36
#define SOC_MODEM_MDM_EICC1_MID 0x17
#define SOC_MODEM_BBP_FBBA2TCM_MID 0x1b
#define SOC_MODEM_BBP_FBBA2DDR_MID 0x1c
#define SOC_MODEM_BBP_GUC_DDR_MID 0x1d
#define SOC_MODEM_BBP_GUC_TCM_MID 0x3d
#define SOC_MODEM_BBP_UL_CIPHER_MID 0x1e
#define SOC_MODEM_BBP_FDAE2TCM_MID 0x1f
#define SOC_MODEM_BBP_FDAE2DDR_MID 0x3f
#define SOC_MODEM_BBP_FDDL2SOC_MID 0x20
#define SOC_MODEM_BBP_FPDF_PDE_C0_MID 0x21
#define SOC_MODEM_BBP_FPDF_PDE_C1_MID 0x22
#define SOC_MODEM_BBP_FASTDMA_CFG_MID 0x23
#define SOC_MODEM_BBP_FASTDMA_RPT_MID 0x25
#define SOC_MODEM_BBP_DBG_MID 0x37
#define SOC_MODEM_BBP_FDDL2DDR_MID 0x38
#define SOC_ISP_1_ISP_CORE_0_MID 0x40
#define SOC_ISP_1_ISP_CORE_1_MID 0x41
#define SOC_ISP_1_ISP_CORE_2_MID 0x42
#define SOC_ISP_1_ISP_CORE_3_MID 0x43
#define SOC_ISP_1_ISP_CORE_4_MID 0x44
#define SOC_ISP_1_ISP_CORE_5_MID 0x45
#define SOC_ISP_1_ISP_CORE_6_MID 0x46
#define SOC_ISP_1_ISP_CORE_7_MID 0x47
#define SOC_ISP_2_ISP_CORE_0_MID 0x48
#define SOC_ISP_2_ISP_CORE_1_MID 0x49
#define SOC_ISP_2_ISP_CORE_2_MID 0x4a
#define SOC_ISP_2_ISP_CORE_3_MID 0x4b
#define SOC_ISP_2_ISP_CORE_4_MID 0x4c
#define SOC_ISP_2_ISP_CORE_5_MID 0x4d
#define SOC_ISP_2_ISP_CORE_6_MID 0x4e
#define SOC_DSS_CMDLIST_MID 0x50
#define SOC_DSS_WR_CH1_MID 0x51
#define SOC_DSS_RD_CH7_MID 0x54
#define SOC_DSS_RD_CH6_MID 0x55
#define SOC_DSS_RD_CH4_MID 0x57
#define SOC_DSS_RD_CH3_MID 0x58
#define SOC_DSS_RD_CH2_MID 0x59
#define SOC_DSS_RD_CH0_DSS_ATGM_MID 0x5b
#define SOC_ISP_ISP_R8_ISP_ATGM_MID 0x5c
#define SOC_IPP_SUBSYS_JPGENC_MID 0x5d
#define SOC_VENC_1_MID 0x60
#define SOC_VENC_2_MID 0x61
#define SOC_VDEC1_VDEC_MID 0x62
#define SOC_VDEC2_MID 0x63
#define SOC_VDEC3_MID 0x64
#define SOC_VDEC4_MID 0x65
#define SOC_VDEC5_MID 0x66
#define SOC_VDEC6_MID 0x67
#define SOC_IVP32_DSP_DSP_CORE_INST_IVP_ATGM_MID 0x69
#define SOC_IVP32_DSP_DSP_CORE_INST_MID SOC_IVP32_DSP_DSP_CORE_INST_IVP_ATGM_MID
#define SOC_IVP32_DSP_DSP_DMA_MID 0x6a
#define SOC_ISP_ISP_A7_CFG_MID 0x6b
#define SOC_IPP_SUBSYS_CMDLIST_MID 0x6c
#define SOC_IPP_SUBSYS_ORB_MID 0x6d
#define SOC_NPU_NPU_ATGM_NPU_MID 0x70
#define SOC_NPU_NPU_MID 0x71
#define SOC_IVP32_DSP_DSP_CORE_DATA_MID 0x74
#define SOC_SYSTEMCACHE_MID 0x76
#define SOC_FCM_M0_M1_MP_MID 0x78
#define SOC_GPU0_NOT_DRM_MID 0x7a
#define SOC_GPU0_DRM_MID 0x7b
#define SOC_IDI2AXI_MID 0x7c
#define SOC_HIEPS_SCE1_MID 0x7d
#define SOC_HIEPS_SCE2_MID 0x7e
#define SOC_HIEPS_PTW_MID 0x7f
#define SOC_MAX_MID 0x80
#define SEC_ASI5_MASK 0x1F
#define SEC_ASI0_MASK 0x1F
#define SEC_ASI0_ASI12_MASK 0x1F
#define SEC_ASI12_MASK 0x1F
#define SEC_ASI3_ASI4_MASK 0x1F
#define SEC_ASI1_ASI2_MASK 0x1F
#define SEC_ASI8_ASI9_MASK 0x1
#define SEC_ASI6_ASI7_MASK 0x1
#define SEC_ASI13_0_ASI13_1_MASK 0x1
#define TZMP2_ASI5_MASK 0x3F
#define TZMP2_ASI0_MASK 0x1F
#define TZMP2_ASI0_ASI12_MASK 0x1F
#define TZMP2_ASI12_MASK 0x1F
#define TZMP2_ASI3_ASI4_MASK 0x1F
#define TZMP2_ASI1_ASI2_MASK 0x1F
#define TZMP2_ASI8_ASI9_MASK 0x1F
#define TZMP2_ASI6_ASI7_MASK 0x1F
#define TZMP2_ASI13_0_ASI13_1_MASK 0x1F
#define SEC_BIT(x) (0x01U << (x))
#define LPMCU_MID (SOC_LPMCU_MID & SEC_ASI5_MASK)
#define IOMCU_M7_MID (SOC_IOMCU_M7_MID & SEC_ASI5_MASK)
#define PERF_STAT_LATMON_MID (SOC_PERF_STAT_MID & SEC_ASI5_MASK)
#define MODEM_IPF_MID (SOC_IPF_MID & SEC_ASI5_MASK)
#define DJTAG_M_TOP_CSSYS_MID (SOC_DJTAG_M_MID & SEC_ASI5_MASK)
#define IOMCU_DMA_AO_TCP_MID (SOC_IOMCU_DMA_MID & SEC_ASI5_MASK)
#define UFS_MID (SOC_UFS_MID & SEC_ASI5_MASK)
#define SD_MID (SOC_SD_MID & SEC_ASI5_MASK)
#define SDIO_MID (SOC_SDIO_MID & SEC_ASI5_MASK)
#define CC712_MID (SOC_CC712_MID & SEC_ASI5_MASK)
#define HSDT_TCU_MID (SOC_HSDT_TCU_MID & SEC_ASI5_MASK)
#define DPC_MID (SOC_DPC_MID & SEC_ASI5_MASK)
#define MODEM_SOCP_MID (SOC_SOCP_MID & SEC_ASI5_MASK)
#define USB31OTG_MID (SOC_USB31OTG_MID & SEC_ASI5_MASK)
#define MODEM_EICC_AP_MID (SOC_MODEM_EICC_AP_MID & SEC_ASI5_MASK)
#define DMAC_MID (SOC_DMAC_MID & SEC_ASI5_MASK)
#define ASP_HIFI_MID (SOC_ASP_HIFI_MID & SEC_ASI5_MASK)
#define PCIE_0_MID (SOC_PCIE_0_MID & SEC_ASI5_MASK)
#define ATGS_MID (SOC_ATGS_MID & SEC_ASI5_MASK)
#define ASP_DMA_USB_HDMI_MID (SOC_ASP_DMA_USB_HDMI_MID & SEC_ASI5_MASK)
#define MODEM_MAA_AP_MID (SOC_MODEM_MAA_AP_MID & SEC_ASI5_MASK)
#define MODEM_SPE_AP_MID (SOC_MODEM_SPE_AP_MID & SEC_ASI5_MASK)
#define MODEM_TSP_CORE_THREAD0_MID (SOC_MODEM_TSP_CORE_THREAD0_MID & SEC_ASI0_MASK)
#define MODEM_TSP_CORE_THREAD1_MID (SOC_MODEM_TSP_CORE_THREAD1_MID & SEC_ASI0_MASK)
#define MODEM_TSP_CORE_THREAD2_MID (SOC_MODEM_TSP_CORE_THREAD2_MID & SEC_ASI0_MASK)
#define MODEM_TSP_CORE_THREAD3_MID (SOC_MODEM_TSP_CORE_THREAD3_MID & SEC_ASI0_MASK)
#define MODEM_TSP_CORE_THREAD4_MID (SOC_MODEM_TSP_CORE_THREAD4_MID & SEC_ASI0_MASK)
#define MODEM_TSP_CORE_THREAD5_MID (SOC_MODEM_TSP_CORE_THREAD5_MID & SEC_ASI0_MASK)
#define MODEM_TSP_CORE_THREAD6_MID (SOC_MODEM_TSP_CORE_THREAD6_MID & SEC_ASI0_MASK)
#define MODEM_TSP_CORE_THREAD7_MID (SOC_MODEM_TSP_CORE_THREAD7_MID & SEC_ASI0_MASK)
#define MODEM_TSP_CORE_PCC_MID (SOC_MODEM_TSP_CORE_PCC_MID & SEC_ASI0_MASK)
#define MODEM_MDM_RRT_MID (SOC_MODEM_MDM_RRT_MID & SEC_ASI0_MASK)
#define MODEM_MDM_CIPHER5G_MID (SOC_MODEM_MDM_CIPHER5G_MID & SEC_ASI0_MASK)
#define MODEM_MDM_LATMON_MID (SOC_MODEM_MDM_LATMON_MID & SEC_ASI0_MASK)
#define ASI0_MODEM_MDM_L2DLE_MID (SOC_MODEM_MDM_L2DLE_MID & SEC_ASI0_ASI12_MASK)
#define ASI12_MODEM_MDM_L2DLE_MID (SOC_MODEM_MDM_L2DLE_MID & SEC_ASI0_ASI12_MASK)
#define MODEM_MDM_EICC0_MID (SOC_MODEM_MDM_EICC0_MID & SEC_ASI0_MASK)
#define MODEM_MDM_EDMA0_MID (SOC_MODEM_MDM_EDMA0_MID & SEC_ASI0_MASK)
#define MODEM_MDM_EDMA1_MID (SOC_MODEM_MDM_EDMA1_MID & SEC_ASI0_MASK)
#define MODEM_MDM_CICOM0_MID (SOC_MODEM_MDM_CICOM0_MID & SEC_ASI0_MASK)
#define MODEM_MDM_UPACC_MID (SOC_MODEM_MDM_UPACC_MID & SEC_ASI0_MASK)
#define MODEM_MDM_EICC1_MID (SOC_MODEM_MDM_EICC1_MID & SEC_ASI0_MASK)
#define MODEM_BBP_FBBA2TCM_MID (SOC_MODEM_BBP_FBBA2TCM_MID & SEC_ASI0_MASK)
#define MODEM_BBP_FBBA2DDR_MID (SOC_MODEM_BBP_FBBA2DDR_MID & SEC_ASI0_MASK)
#define MODEM_BBP_GUC_DDR_MID (SOC_MODEM_BBP_GUC_DDR_MID & SEC_ASI0_MASK)
#define MODEM_BBP_GUC_TCM_MID (SOC_MODEM_BBP_GUC_TCM_MID & SEC_ASI0_MASK)
#define MODEM_BBP_UL_CIPHER_MID (SOC_MODEM_BBP_UL_CIPHER_MID & SEC_ASI0_MASK)
#define MODEM_BBP_FDAE2TCM_MID (SOC_MODEM_BBP_FDAE2TCM_MID & SEC_ASI0_MASK)
#define ASI0_MODEM_BBP_FDAE2DDR_MID (SOC_MODEM_BBP_FDAE2DDR_MID & SEC_ASI0_ASI12_MASK)
#define ASI12_MODEM_BBP_FDAE2DDR_MID (SOC_MODEM_BBP_FDAE2DDR_MID & SEC_ASI0_ASI12_MASK)
#define MODEM_BBP_FDDL2SOC_MID (SOC_MODEM_BBP_FDDL2SOC_MID & SEC_ASI0_MASK)
#define MODEM_BBP_FPDF_PDE_C0_MID (SOC_MODEM_BBP_FPDF_PDE_C0_MID & SEC_ASI0_MASK)
#define MODEM_BBP_FPDF_PDE_C1_MID (SOC_MODEM_BBP_FPDF_PDE_C1_MID & SEC_ASI0_MASK)
#define MODEM_BBP_FASTDMA_CFG_MID (SOC_MODEM_BBP_FASTDMA_CFG_MID & SEC_ASI0_MASK)
#define MODEM_BBP_FASTDMA_RPT_MID (SOC_MODEM_BBP_FASTDMA_RPT_MID & SEC_ASI0_MASK)
#define MODEM_BBP_DBG_MID (SOC_MODEM_BBP_DBG_MID & SEC_ASI12_MASK)
#define MODEM_BBP_FDDL2DDR_MID (SOC_MODEM_BBP_FDDL2DDR_MID & SEC_ASI12_MASK)
#define ISP_1_ISP_CORE_0_MID (SOC_ISP_1_ISP_CORE_0_MID & SEC_ASI3_ASI4_MASK)
#define ISP_1_ISP_CORE_1_MID (SOC_ISP_1_ISP_CORE_1_MID & SEC_ASI3_ASI4_MASK)
#define ISP_1_ISP_CORE_2_MID (SOC_ISP_1_ISP_CORE_2_MID & SEC_ASI3_ASI4_MASK)
#define ISP_1_ISP_CORE_3_MID (SOC_ISP_1_ISP_CORE_3_MID & SEC_ASI3_ASI4_MASK)
#define ISP_1_ISP_CORE_4_MID (SOC_ISP_1_ISP_CORE_4_MID & SEC_ASI3_ASI4_MASK)
#define ISP_1_ISP_CORE_5_MID (SOC_ISP_1_ISP_CORE_5_MID & SEC_ASI3_ASI4_MASK)
#define ISP_1_ISP_CORE_6_MID (SOC_ISP_1_ISP_CORE_6_MID & SEC_ASI3_ASI4_MASK)
#define ISP_1_ISP_CORE_7_MID (SOC_ISP_1_ISP_CORE_7_MID & SEC_ASI3_ASI4_MASK)
#define ISP_2_ISP_CORE_0_MID (SOC_ISP_2_ISP_CORE_0_MID & SEC_ASI3_ASI4_MASK)
#define ISP_2_ISP_CORE_1_MID (SOC_ISP_2_ISP_CORE_1_MID & SEC_ASI3_ASI4_MASK)
#define ISP_2_ISP_CORE_2_MID (SOC_ISP_2_ISP_CORE_2_MID & SEC_ASI3_ASI4_MASK)
#define ISP_2_ISP_CORE_3_MID (SOC_ISP_2_ISP_CORE_3_MID & SEC_ASI3_ASI4_MASK)
#define ISP_2_ISP_CORE_4_MID (SOC_ISP_2_ISP_CORE_4_MID & SEC_ASI3_ASI4_MASK)
#define ISP_2_ISP_CORE_5_MID (SOC_ISP_2_ISP_CORE_5_MID & SEC_ASI3_ASI4_MASK)
#define ISP_2_ISP_CORE_6_MID (SOC_ISP_2_ISP_CORE_6_MID & SEC_ASI3_ASI4_MASK)
#define DSS_CMDLIST_MID (SOC_DSS_CMDLIST_MID & SEC_ASI3_ASI4_MASK)
#define DSS_WR_CH1_MID (SOC_DSS_WR_CH1_MID & SEC_ASI3_ASI4_MASK)
#define DSS_RD_CH7_MID (SOC_DSS_RD_CH7_MID & SEC_ASI3_ASI4_MASK)
#define DSS_RD_CH6_MID (SOC_DSS_RD_CH6_MID & SEC_ASI3_ASI4_MASK)
#define DSS_RD_CH4_MID (SOC_DSS_RD_CH4_MID & SEC_ASI3_ASI4_MASK)
#define DSS_RD_CH3_MID (SOC_DSS_RD_CH3_MID & SEC_ASI3_ASI4_MASK)
#define DSS_RD_CH2_MID (SOC_DSS_RD_CH2_MID & SEC_ASI3_ASI4_MASK)
#define DSS_RD_CH0_DSS_ATGM_MID (SOC_DSS_RD_CH0_DSS_ATGM_MID & SEC_ASI3_ASI4_MASK)
#define ISP_ISP_R8_ISP_ATGM_MID (SOC_ISP_ISP_R8_ISP_ATGM_MID & SEC_ASI3_ASI4_MASK)
#define IPP_SUBSYS_JPGENC_MID (SOC_IPP_SUBSYS_JPGENC_MID & SEC_ASI3_ASI4_MASK)
#define VENC_1_MID (SOC_VENC_1_MID & SEC_ASI1_ASI2_MASK)
#define VENC_2_MID (SOC_VENC_2_MID & SEC_ASI1_ASI2_MASK)
#define VDEC1_VDEC_MID (SOC_VDEC1_VDEC_MID & SEC_ASI1_ASI2_MASK)
#define VDEC2_MID (SOC_VDEC2_MID & SEC_ASI1_ASI2_MASK)
#define VDEC3_MID (SOC_VDEC3_MID & SEC_ASI1_ASI2_MASK)
#define VDEC4_MID (SOC_VDEC4_MID & SEC_ASI1_ASI2_MASK)
#define VDEC5_MID (SOC_VDEC5_MID & SEC_ASI1_ASI2_MASK)
#define VDEC6_MID (SOC_VDEC6_MID & SEC_ASI1_ASI2_MASK)
#define IVP32_DSP_DSP_CORE_INST_IVP_ATGM_MID (SOC_IVP32_DSP_DSP_CORE_INST_IVP_ATGM_MID & SEC_ASI1_ASI2_MASK)
#define IVP32_DSP_DSP_DMA_MID (SOC_IVP32_DSP_DSP_DMA_MID & SEC_ASI1_ASI2_MASK)
#define IPP_SUBSYS_CMDLIST_MID (SOC_IPP_SUBSYS_CMDLIST_MID & SEC_ASI3_ASI4_MASK)
#define IPP_SUBSYS_ORB_MID (SOC_IPP_SUBSYS_ORB_MID & SEC_ASI3_ASI4_MASK)
#define NPU_NPU_ATGM_NPU_MID (SOC_NPU_NPU_ATGM_NPU_MID & SEC_ASI8_ASI9_MASK)
#define NPU_NPU_MID (SOC_NPU_NPU_MID & SEC_ASI8_ASI9_MASK)
#define IVP32_DSP_DSP_CORE_DATA_MID (SOC_IVP32_DSP_DSP_CORE_DATA_MID & SEC_ASI1_ASI2_MASK)
#define FCM_M0_M1_MP_MID (SOC_FCM_M0_M1_MP_MID & SEC_ASI6_ASI7_MASK)
#define GPU0_NOT_DRM_MID (SOC_GPU0_NOT_DRM_MID & SEC_ASI13_0_ASI13_1_MASK)
#define GPU0_DRM_MID (SOC_GPU0_DRM_MID & SEC_ASI13_0_ASI13_1_MASK)
#define IDI2AXI_MID (SOC_IDI2AXI_MID & SEC_ASI3_ASI4_MASK)
#define HIEPS_SCE1_MID (SOC_HIEPS_SCE1_MID & SEC_ASI1_ASI2_MASK)
#define HIEPS_SCE2_MID (SOC_HIEPS_SCE2_MID & SEC_ASI1_ASI2_MASK)
#define HIEPS_PTW_MID (SOC_HIEPS_PTW_MID & SEC_ASI1_ASI2_MASK)
#define ASP_ALL (SEC_BIT(ASP_HIFI_MID) | SEC_BIT(ASP_DMA_USB_HDMI_MID))
#define MODEM_ALL (SEC_BIT(MODEM_TSP_CORE_THREAD0_MID) | SEC_BIT(MODEM_TSP_CORE_THREAD1_MID) | \
  SEC_BIT(MODEM_TSP_CORE_THREAD2_MID) | SEC_BIT(MODEM_TSP_CORE_THREAD3_MID) | \
  SEC_BIT(MODEM_TSP_CORE_THREAD4_MID) | SEC_BIT(MODEM_TSP_CORE_THREAD5_MID) | \
  SEC_BIT(MODEM_TSP_CORE_THREAD6_MID) | SEC_BIT(MODEM_TSP_CORE_THREAD7_MID) | \
  SEC_BIT(MODEM_TSP_CORE_PCC_MID) | SEC_BIT(MODEM_MDM_RRT_MID) | \
  SEC_BIT(MODEM_MDM_CIPHER5G_MID) | SEC_BIT(MODEM_MDM_LATMON_MID) | \
  SEC_BIT(MODEM_MDM_L2DLE_MID) | SEC_BIT(MODEM_MDM_EICC0_MID) | \
  SEC_BIT(MODEM_MDM_EDMA0_MID) | SEC_BIT(MODEM_MDM_EDMA1_MID) | \
  SEC_BIT(MODEM_MDM_CICOM0_MID) | SEC_BIT(MODEM_MDM_UPACC_MID) | \
  SEC_BIT(MODEM_MDM_EICC1_MID) | SEC_BIT(MODEM_BBP_FBBA2TCM_MID) | \
  SEC_BIT(MODEM_BBP_FBBA2DDR_MID) | SEC_BIT(MODEM_BBP_GUC_DDR_MID) | \
  SEC_BIT(MODEM_BBP_GUC_TCM_MID) | SEC_BIT(MODEM_BBP_UL_CIPHER_MID) | \
  SEC_BIT(MODEM_BBP_FDAE2TCM_MID) | SEC_BIT(MODEM_BBP_FDAE2DDR_MID) | \
  SEC_BIT(MODEM_BBP_FDDL2SOC_MID) | SEC_BIT(MODEM_BBP_FPDF_PDE_C0_MID) | \
  SEC_BIT(MODEM_BBP_FASTDMA_CFG_MID) | SEC_BIT(MODEM_BBP_FASTDMA_RPT_MID) | \
  SEC_BIT(MODEM_BBP_DBG_MID) | SEC_BIT(MODEM_BBP_FDDL2DDR_MID) | \
  SEC_BIT(MODEM_EICC_AP_MID) | SEC_BIT(MODEM_MAA_AP_MID) | \
  SEC_BIT(MODEM_SPE_AP_MID) | SEC_BIT(ASI0_MODEM_MDM_L2DLE_MID) | \
  SEC_BIT(ASI0_MODEM_BBP_FDAE2DDR_MID) | SEC_BIT(MODEM_IPF_MID) | \
  SEC_BIT(MODEM_SOCP_MID))
#define ISP_1_ALL (SEC_BIT(ISP_1_ISP_CORE_0_MID) | SEC_BIT(ISP_1_ISP_CORE_1_MID) | \
  SEC_BIT(ISP_1_ISP_CORE_2_MID) | SEC_BIT(ISP_1_ISP_CORE_3_MID) | \
  SEC_BIT(ISP_1_ISP_CORE_4_MID) | SEC_BIT(ISP_1_ISP_CORE_5_MID) | \
  SEC_BIT(ISP_1_ISP_CORE_6_MID) | SEC_BIT(ISP_1_ISP_CORE_7_MID))
#define ISP_2_ALL (SEC_BIT(ISP_2_ISP_CORE_0_MID) | SEC_BIT(ISP_2_ISP_CORE_1_MID) | \
  SEC_BIT(ISP_2_ISP_CORE_2_MID) | SEC_BIT(ISP_2_ISP_CORE_3_MID) | \
  SEC_BIT(ISP_2_ISP_CORE_4_MID) | SEC_BIT(ISP_2_ISP_CORE_5_MID) | \
  SEC_BIT(ISP_2_ISP_CORE_6_MID))
#define DSS_ALL (SEC_BIT(DSS_CMDLIST_MID) | SEC_BIT(DSS_WR_CH1_MID) | \
  SEC_BIT(DSS_RD_CH7_MID) | SEC_BIT(DSS_RD_CH6_MID) | \
  SEC_BIT(DSS_RD_CH4_MID) | SEC_BIT(DSS_RD_CH3_MID) | \
  SEC_BIT(DSS_RD_CH2_MID) | SEC_BIT(DSS_RD_CH0_DSS_ATGM_MID))
#define VENC_ALL (SEC_BIT(VENC_1_MID) | SEC_BIT(VENC_2_MID))
#define VDEC_ALL (SEC_BIT(VDEC1_VDEC_MID) | SEC_BIT(VDEC2_MID) | \
      SEC_BIT(VDEC3_MID) | SEC_BIT(VDEC4_MID) | \
                    SEC_BIT(VDEC5_MID) | SEC_BIT(VDEC6_MID))
#define ISP_ALL (SEC_BIT(ISP_1_ISP_CORE_0_MID) | SEC_BIT(ISP_1_ISP_CORE_1_MID) | \
  SEC_BIT(ISP_1_ISP_CORE_2_MID) | SEC_BIT(ISP_1_ISP_CORE_3_MID) | \
  SEC_BIT(ISP_1_ISP_CORE_4_MID) | SEC_BIT(ISP_1_ISP_CORE_5_MID) | \
  SEC_BIT(ISP_1_ISP_CORE_6_MID) | SEC_BIT(ISP_1_ISP_CORE_7_MID) | \
  SEC_BIT(ISP_2_ISP_CORE_0_MID) | SEC_BIT(ISP_2_ISP_CORE_1_MID) | \
  SEC_BIT(ISP_2_ISP_CORE_2_MID) | SEC_BIT(ISP_2_ISP_CORE_3_MID) | \
  SEC_BIT(ISP_2_ISP_CORE_4_MID) | SEC_BIT(ISP_2_ISP_CORE_5_MID) | \
  SEC_BIT(ISP_2_ISP_CORE_6_MID))
#define IPP_SUBSYS_ALL (SEC_BIT(IPP_SUBSYS_JPGENC_MID) | SEC_BIT(IPP_SUBSYS_CMDLIST_MID) | \
  SEC_BIT(IPP_SUBSYS_ORB_MID))
#define IVP_ALL (SEC_BIT(IVP32_DSP_DSP_CORE_INST_IVP_ATGM_MID) | SEC_BIT(IVP32_DSP_DSP_DMA_MID) | \
  SEC_BIT(IVP32_DSP_DSP_CORE_DATA_MID))
#define CPU_ALL (SEC_BIT(FCM_M0_M1_MP_MID))
#define NPU_ALL (SEC_BIT(NPU_NPU_ATGM_NPU_MID) | SEC_BIT(NPU_NPU_MID))
#define GPU_ALL (SEC_BIT(GPU0_NOT_DRM_MID) | SEC_BIT(GPU0_DRM_MID))
#define FORBID_MID 0x0
#define ALL_MID 0xFFFFFFFF
#endif
