#ifndef __SOC_EFUSE2_INTERFACE_H__
#define __SOC_EFUSE2_INTERFACE_H__ 
#ifdef __cplusplus
    #if __cplusplus
        extern "C" {
    #endif
#endif
#if defined(CONFIG_EFUSE_IN_XLOADER)
enum {
 EFUSE2_NV_COUNTER = 0,
 EFUSE2_SECURE_BOOT,
 EFUSE2_SECENGEPS_SEL,
 EFUSE2_GMROTPK_HASH,
 EFUSE2_GJROTPK_HASH,
 EFUSE2_PATCH_SHA256,
 EFUSE2_MA_DEBUG,
 EFUSE2_GM_ROTPK_ZEROES,
 EFUSE2_GJ_ROTPK_ZEROES,
 EFUSE2_LCS_EPS,
 EFUSE2_SM234_EN = 10,
 EFUSE2_KEYDEBUG_DIS,
 EFUSE2_DEBUG_DIS,
 EFUSE2_GLBKEY_EPSGID,
 EFUSE2_CRC_EPSGID,
 EFUSE2_ZEROES_EPSGID,
 EFUSE2_EPS_KDR,
 EFUSE2_CRC_EPSKDR,
 EFUSE2_ZEROES_EPSKDR,
 EFUSE2_CRYPTOENHANCE_GMPOSK,
 EFUSE2_CRC_GMPOSK = 20,
 EFUSE2_ZEROES_GMPOSK,
 EFUSE2_APBPGM_DIS,
 EFUSE2_PAD_DIS,
 EFUSE2_ENC_EFC,
 EFUSE2_LOCK_GMJROTPKZEROES,
 EFUSE2_PATCH_GJROTPK_WRLOCK,
 EFUSE2_LOCK_GMROTPKHASH,
 EFUSE2_LOCK_SECUREBOOT,
 EFUSE2_LOCK_SECENGEPSSEL,
 EFUSE2_LOCK_GID = 30,
 EFUSE2_LOCK_KDR,
 EFUSE2_LOCK_GMPOSK,
 EFUSE2_LOCK_MADEBUG,
 EFUSE2_UAPP_KEYREVOKE,
 EFUSE2_UAPP_ENABLE,
 EFUSE2_UAPP_CONSISTENCY,
};
#elif defined(CONFIG_EFUSE_IN_BL2)
enum {
 EFUSE2_NV_COUNTER = 0,
 EFUSE2_SECURE_BOOT,
 EFUSE2_SECENGEPS_SEL,
 EFUSE2_GMROTPK_HASH,
 EFUSE2_GJROTPK_HASH,
 EFUSE2_PATCH_SHA256,
 EFUSE2_MA_DEBUG,
 EFUSE2_GM_ROTPK_ZEROES,
 EFUSE2_GJ_ROTPK_ZEROES,
 EFUSE2_LCS_EPS,
 EFUSE2_SM234_EN = 10,
 EFUSE2_KEYDEBUG_DIS,
 EFUSE2_DEBUG_DIS,
 EFUSE2_GLBKEY_EPSGID,
 EFUSE2_CRC_EPSGID,
 EFUSE2_ZEROES_EPSGID,
 EFUSE2_EPS_KDR,
 EFUSE2_CRC_EPSKDR,
 EFUSE2_ZEROES_EPSKDR,
 EFUSE2_CRYPTOENHANCE_GMPOSK,
 EFUSE2_CRC_GMPOSK = 20,
 EFUSE2_ZEROES_GMPOSK,
 EFUSE2_APBPGM_DIS,
 EFUSE2_PAD_DIS,
 EFUSE2_ENC_EFC,
 EFUSE2_LOCK_GMJROTPKZEROES,
 EFUSE2_PATCH_GJROTPK_WRLOCK,
 EFUSE2_LOCK_GMROTPKHASH,
 EFUSE2_LOCK_SECUREBOOT,
 EFUSE2_LOCK_SECENGEPSSEL,
 EFUSE2_LOCK_GID = 30,
 EFUSE2_LOCK_KDR,
 EFUSE2_LOCK_GMPOSK,
 EFUSE2_LOCK_MADEBUG,
 EFUSE2_UAPP_KEYREVOKE,
 EFUSE2_UAPP_ENABLE,
 EFUSE2_UAPP_CONSISTENCY,
#if defined(CONFIG_DEBUG_EFUSE)
 EFUSE2_DEBUG_ID,
#endif
};
#elif defined(CONFIG_EFUSE_IN_BL31)
enum {
 EFUSE2_NV_COUNTER = 0,
 EFUSE2_SECURE_BOOT,
 EFUSE2_SECENGEPS_SEL,
 EFUSE2_GMROTPK_HASH,
 EFUSE2_GJROTPK_HASH,
 EFUSE2_PATCH_SHA256,
 EFUSE2_MA_DEBUG,
 EFUSE2_GM_ROTPK_ZEROES,
 EFUSE2_GJ_ROTPK_ZEROES,
 EFUSE2_LCS_EPS,
 EFUSE2_SM234_EN = 10,
 EFUSE2_KEYDEBUG_DIS,
 EFUSE2_DEBUG_DIS,
 EFUSE2_GLBKEY_EPSGID,
 EFUSE2_CRC_EPSGID,
 EFUSE2_ZEROES_EPSGID,
 EFUSE2_EPS_KDR,
 EFUSE2_CRC_EPSKDR,
 EFUSE2_ZEROES_EPSKDR,
 EFUSE2_CRYPTOENHANCE_GMPOSK,
 EFUSE2_CRC_GMPOSK = 20,
 EFUSE2_ZEROES_GMPOSK,
 EFUSE2_APBPGM_DIS,
 EFUSE2_PAD_DIS,
 EFUSE2_ENC_EFC,
 EFUSE2_LOCK_GMJROTPKZEROES,
 EFUSE2_PATCH_GJROTPK_WRLOCK,
 EFUSE2_LOCK_GMROTPKHASH,
 EFUSE2_LOCK_SECUREBOOT,
 EFUSE2_LOCK_SECENGEPSSEL,
 EFUSE2_LOCK_GID = 30,
 EFUSE2_LOCK_KDR,
 EFUSE2_LOCK_GMPOSK,
 EFUSE2_LOCK_MADEBUG,
 EFUSE2_UAPP_KEYREVOKE,
 EFUSE2_UAPP_ENABLE,
 EFUSE2_UAPP_CONSISTENCY,
};
#elif defined(CONFIG_EFUSE_IN_HIBENCH)
enum {
 EFUSE2_NV_COUNTER = 0,
 EFUSE2_SECURE_BOOT,
 EFUSE2_SECENGEPS_SEL,
 EFUSE2_GMROTPK_HASH,
 EFUSE2_GJROTPK_HASH,
 EFUSE2_PATCH_SHA256,
 EFUSE2_MA_DEBUG,
 EFUSE2_GM_ROTPK_ZEROES,
 EFUSE2_GJ_ROTPK_ZEROES,
 EFUSE2_LCS_EPS,
 EFUSE2_SM234_EN = 10,
 EFUSE2_KEYDEBUG_DIS,
 EFUSE2_DEBUG_DIS,
 EFUSE2_GLBKEY_EPSGID,
 EFUSE2_CRC_EPSGID,
 EFUSE2_ZEROES_EPSGID,
 EFUSE2_EPS_KDR,
 EFUSE2_CRC_EPSKDR,
 EFUSE2_ZEROES_EPSKDR,
 EFUSE2_CRYPTOENHANCE_GMPOSK,
 EFUSE2_CRC_GMPOSK = 20,
 EFUSE2_ZEROES_GMPOSK,
 EFUSE2_APBPGM_DIS,
 EFUSE2_PAD_DIS,
 EFUSE2_ENC_EFC,
 EFUSE2_LOCK_GMJROTPKZEROES,
 EFUSE2_PATCH_GJROTPK_WRLOCK,
 EFUSE2_LOCK_GMROTPKHASH,
 EFUSE2_LOCK_SECUREBOOT,
 EFUSE2_LOCK_SECENGEPSSEL,
 EFUSE2_LOCK_GID = 30,
 EFUSE2_LOCK_KDR,
 EFUSE2_LOCK_GMPOSK,
 EFUSE2_LOCK_MADEBUG,
 EFUSE2_UAPP_KEYREVOKE,
 EFUSE2_UAPP_ENABLE,
 EFUSE2_UAPP_CONSISTENCY,
};
#endif
#define EFUSE2_NV_COUNTER_START 0
#define EFUSE2_NV_COUNTER_SIZE 64
#define EFUSE2_SECURE_BOOT_START 64
#define EFUSE2_SECURE_BOOT_SIZE 320
#define EFUSE2_SECENGEPS_SEL_START 384
#define EFUSE2_SECENGEPS_SEL_SIZE 32
#define EFUSE2_UAPP_KEYREVOKE_START 2428
#define EFUSE2_UAPP_KEYREVOKE_SIZE 32
#define EFUSE2_UAPP_ENABLE_START 2460
#define EFUSE2_UAPP_ENABLE_SIZE 1
#define EFUSE2_UAPP_CONSISTENCY_START 2461
#define EFUSE2_UAPP_CONSISTENCY_SIZE 1
#define EFUSE2_GMROTPK_HASH_START 2496
#define EFUSE2_GMROTPK_HASH_SIZE 256
#define EFUSE2_GJROTPK_HASH_START 2752
#define EFUSE2_GJROTPK_HASH_SIZE 256
#define EFUSE2_PATCH_SHA256_START 3008
#define EFUSE2_PATCH_SHA256_SIZE 256
#define EFUSE2_MA_DEBUG_START 3264
#define EFUSE2_MA_DEBUG_SIZE 32
#define EFUSE2_GM_ROTPK_ZEROES_START 3296
#define EFUSE2_GM_ROTPK_ZEROES_SIZE 8
#define EFUSE2_GJ_ROTPK_ZEROES_START 3304
#define EFUSE2_GJ_ROTPK_ZEROES_SIZE 8
#define EFUSE2_LCS_EPS_START 3335
#define EFUSE2_LCS_EPS_SIZE 16
#define EFUSE2_SM234_EN_START 3351
#define EFUSE2_SM234_EN_SIZE 1
#define EFUSE2_KEYDEBUG_DIS_START 3352
#define EFUSE2_KEYDEBUG_DIS_SIZE 4
#define EFUSE2_DEBUG_DIS_START 3356
#define EFUSE2_DEBUG_DIS_SIZE 4
#define EFUSE2_GLBKEY_EPSGID_START 3392
#define EFUSE2_GLBKEY_EPSGID_SIZE 128
#define EFUSE2_CRC_EPSGID_START 3520
#define EFUSE2_CRC_EPSGID_SIZE 16
#define EFUSE2_ZEROES_EPSGID_START 3536
#define EFUSE2_ZEROES_EPSGID_SIZE 7
#define EFUSE2_EPS_KDR_START 3552
#define EFUSE2_EPS_KDR_SIZE 256
#define EFUSE2_CRC_EPSKDR_START 3808
#define EFUSE2_CRC_EPSKDR_SIZE 32
#define EFUSE2_ZEROES_EPSKDR_START 3840
#define EFUSE2_ZEROES_EPSKDR_SIZE 8
#define EFUSE2_CRYPTOENHANCE_GMPOSK_START 3872
#define EFUSE2_CRYPTOENHANCE_GMPOSK_SIZE 128
#define EFUSE2_CRC_GMPOSK_START 4000
#define EFUSE2_CRC_GMPOSK_SIZE 16
#define EFUSE2_ZEROES_GMPOSK_START 4016
#define EFUSE2_ZEROES_GMPOSK_SIZE 7
#define EFUSE2_APBPGM_DIS_START 4064
#define EFUSE2_APBPGM_DIS_SIZE 1
#define EFUSE2_PAD_DIS_START 4065
#define EFUSE2_PAD_DIS_SIZE 1
#define EFUSE2_ENC_EFC_START 4081
#define EFUSE2_ENC_EFC_SIZE 2
#define EFUSE2_LOCK_GMJROTPKZEROES_START 4086
#define EFUSE2_LOCK_GMJROTPKZEROES_SIZE 1
#define EFUSE2_LOCK_MADEBUG_START 4087
#define EFUSE2_LOCK_MADEBUG_SIZE 1
#define EFUSE2_PATCH_GJROTPK_WRLOCK_START 4088
#define EFUSE2_PATCH_GJROTPK_WRLOCK_SIZE 2
#define EFUSE2_LOCK_GMROTPKHASH_START 4090
#define EFUSE2_LOCK_GMROTPKHASH_SIZE 1
#define EFUSE2_LOCK_SECUREBOOT_START 4091
#define EFUSE2_LOCK_SECUREBOOT_SIZE 1
#define EFUSE2_LOCK_SECENGEPSSEL_START 4092
#define EFUSE2_LOCK_SECENGEPSSEL_SIZE 1
#define EFUSE2_LOCK_GID_START 4093
#define EFUSE2_LOCK_GID_SIZE 1
#define EFUSE2_LOCK_KDR_START 4094
#define EFUSE2_LOCK_KDR_SIZE 1
#define EFUSE2_LOCK_GMPOSK_START 4095
#define EFUSE2_LOCK_GMPOSK_SIZE 1
#define EFUSE2_MAX_SIZE 4096
#define EFUSE2_ITEM_MAX 320
#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif
#endif
