#ifndef __DB_REG_REG_OFFSET_FIELD_H__
#define __DB_REG_REG_OFFSET_FIELD_H__ 
#define DB_REG_DB_INT_SUMMARY_LEN 32
#define DB_REG_DB_INT_SUMMARY_OFFSET 0
#define DB_REG_DB_INT_MASK0_LEN 32
#define DB_REG_DB_INT_MASK0_OFFSET 0
#define DB_REG_DB_INT_MASK1_LEN 32
#define DB_REG_DB_INT_MASK1_OFFSET 0
#define DB_REG_DB_INT_MASK2_LEN 32
#define DB_REG_DB_INT_MASK2_OFFSET 0
#define DB_REG_DB_INT_MASK3_LEN 32
#define DB_REG_DB_INT_MASK3_OFFSET 0
#define DB_REG_DB_INT_STATUS0_LEN 32
#define DB_REG_DB_INT_STATUS0_OFFSET 0
#define DB_REG_DB_INT_STATUS1_LEN 32
#define DB_REG_DB_INT_STATUS1_OFFSET 0
#define DB_REG_DB_INT_STATUS2_LEN 32
#define DB_REG_DB_INT_STATUS2_OFFSET 0
#define DB_REG_DB_INT_STATUS3_LEN 32
#define DB_REG_DB_INT_STATUS3_OFFSET 0
#define DB_REG_DB_SEC_EN_LEN 1
#define DB_REG_DB_SEC_EN_OFFSET 0
#endif
