#ifndef __TRIM_SERVICES_ID_H__
#define __TRIM_SERVICES_ID_H__ 
enum trim_service_idx {
 BL2_SYSTEM_PROFILE_UPDATE,
 BL2_CLUSTER_PROFILE_UPDATE,
 BL2_CLUSTER_PA_MARGIN_UPDATE,
 BL2_CLUSTER_GET_AVS_DATA,
 TRIM_SERVICE_IDX_MAX,
};
#endif
