#ifndef __TSENSOR_SERVICES_ID_H__
#define __TSENSOR_SERVICES_ID_H__ 
enum tsensor_service_idx {
 BL2_TSENSOR_GET_TEMP,
 BL2_TSENSOR_CLR_INT,
 BL2_TSENSOR_ENABLE_INT,
 BL2_TSENSOR_DISABLE_INT,
 BL2_TSENSOR_SET_TEMP_ALARM_THRESHOLD,
 BL2_TSENSOR_GET_TEMP_ALARM_THRESHOLD,
 TSENSOR_SERVICE_IDX_MAX,
};
#endif
