       
#ifndef __TSENSOR_TABLE_H__
#define __TSENSOR_TABLE_H__ 
#ifdef __cplusplus
 #if __cplusplus
  extern "C" {
 #endif
#endif
#include <tsensor_interface.h>
#define BIG_TSENSOR_NUM 5
static unsigned char g_remote_tsensor_num = 7;
static unsigned char g_tsensor_table[TSENSOR_NUM_MAX][BIG_TSENSOR_NUM] = {
  {LOCAL_SENSOR_M0, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX},
  {FCM0_SENSOR, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX},
  {FCM1_SENSOR, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX},
  {GPU_SENSOR_0, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX},
  {MDM0_SENSOR, PDF_SENSOR, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX},
  {NPU_SENSOR_0, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX},
  {LOCAL_SENSOR_M0, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX, SENSOR_UNKNOWN_MAX},
};
static enum sensor_table local_sensor = LOCAL_SENSOR_M0;
#ifdef __cplusplus
 #if __cplusplus
  }
 #endif
#endif
#endif
