#ifndef __XLOADER_SEGMENT_H__
#define __XLOADER_SEGMENT_H__ 
#include "bl31_platform_memory_def.h"
#define XLOADER_BUF_ADDR ATF_BL31_RAM_ADDR
#define XLOADER_BUF_SIZE ATF_BL31_RAM_SIZE
#define XLOADER_SECTION_TYPE_NUM 3
enum xloader_segment {
 NULL_SEGMENT,
 TEXT_SEGMENT,
 DATA_SEGMENT,
 SECDBG_SEGMENT,
 DDR_VRL_SEGMENT,
 DDR_SEGMENT,
 BSS_SEGMENT,
 THIRD_VRL_SEGMENT,
 THIRD_SEGMENT,
 MAX_SEGMENT_NUM,
};
#endif
