#ifndef __XLOADER_MEMORY_MAP_H__
#define __XLOADER_MEMORY_MAP_H__ 
#define SIZE_1KB 1024
#define VRL_SIZE (4 * SIZE_1KB)
#define SEC_PRELOADER_IMAGE_MAX_SIZE (128 * SIZE_1KB)
#define PRELOADER_IMAGE_MAX_SIZE (SEC_PRELOADER_IMAGE_MAX_SIZE - VRL_SIZE)
#define XLOADER_IMAGE_MAX_SIZE (300 * SIZE_1KB)
#define SEC_XLOADER_IMAGE_MAX_SIZE (XLOADER_IMAGE_MAX_SIZE + VRL_SIZE)
#define RESERVED_XLOADER_PARTITION_MAX (1 * SIZE_1KB * SIZE_1KB)
#define PRELOADER_MAGIC2 "PRELOADER!"
#define PRELOADER_MAGIC2_OFFSET 0xCUL
#define SEC_PRELOADER_IMG_BASE 0x22000
#define PRELOADER_IMAGE_BASE (SEC_PRELOADER_IMG_BASE + VRL_SIZE)
#define PRELOADER_ENTRY_BASE PRELOADER_IMAGE_BASE
#define PRELOADER_ENTRY_SIZE 0x100
#define SECINFO_CTX_LPRAM_ADDR (PRELOADER_ENTRY_BASE + PRELOADER_ENTRY_SIZE)
#define SECINFO_CTX_LPRAM_SIZE 0x100
#define LOG_BUFF_BASE (SECINFO_CTX_LPRAM_ADDR + SECINFO_CTX_LPRAM_SIZE)
#define PRELOADER_LOG_BUFF_SIZE 0x1000
#define PRELOADER_BOOT_XLOADER_BASE (LOG_BUFF_BASE + PRELOADER_LOG_BUFF_SIZE)
#define PRELOADER_BOOT_XLOADER_SIZE 0x600
#define XLOADER_LOAD_ADDR (PRELOADER_BOOT_XLOADER_BASE + PRELOADER_BOOT_XLOADER_SIZE)
#define XLOADER_LOG_BUFF_SIZE (PRELOADER_LOG_BUFF_SIZE + PRELOADER_BOOT_XLOADER_SIZE)
#define PRELOADER_HEADER_SIZE (PRELOADER_ENTRY_SIZE + SECINFO_CTX_LPRAM_SIZE + XLOADER_LOG_BUFF_SIZE)
#endif
