# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_REVERSE_CHARGE_PD) += reverse_charge_pd.o
obj-$(CONFIG_REVERSE_CHARGE) += reverse_charge.o
obj-$(CONFIG_REVERSE_CHARGE) += reverse_charge_boost.o
obj-$(CONFIG_REVERSE_CHARGE) += reverse_charge_protocol.o
obj-$(CONFIG_REVERSE_CHARGE) += reverse_charge_scp_auth.o