set(CFG_PRODUCT_NAME "charlotte")

set(CFG_PRODUCT_CFG_CHIP_SOLUTION_NAME "Balong")

set(CFG_BUILD_TYPE RELEASE)

set(CFG_PRODUCT_VERSION V100R001C00B010)

set(CFG_PRODUCT_VERSION_STR "V100R001C00B010")

set(CFG_PRODUCT_FULL_VERSION_STR "Baltimore V100R001C50SPC303")

set(CFG_PRODUCT_DLOAD_SOFTWARE_VER "21C50SPC303CP0000")

set(CFG_PLATFORM charlotte)

set(CFG_PLATFORM_HISI_BALONG charlotte)

set(CFG_MODEM_FUSION_VERSION true)

set(CFG_NV_VERSION charlotte)

