
CFG_PRODUCT_NAME := "charlotte"

CFG_PRODUCT_CFG_CHIP_SOLUTION_NAME := "Balong"

CFG_BUILD_TYPE := RELEASE

CFG_PRODUCT_VERSION := V100R001C00B010

CFG_PRODUCT_VERSION_STR := "V100R001C00B010"

CFG_PRODUCT_FULL_VERSION_STR := "Baltimore V100R001C50SPC303"

CFG_PRODUCT_DLOAD_SOFTWARE_VER := "21C50SPC303CP0000"

CFG_PLATFORM := charlotte

CFG_PLATFORM_HISI_BALONG := charlotte

CFG_MODEM_FUSION_VERSION := true

CFG_NV_VERSION := charlotte
