# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_HONOR_DUBAI_COMMON) += dubaihook/
obj-$(CONFIG_KSTATE_COMMON)	+= kstatehook/
