
CFG_PRODUCT_CONTROL_VERSION := "141"

CFG_PRODUCT_DIFF_NV_FILTER := charlotte_udp

CFG_PRODUCT_NV_FILE_MAX_SIZE := /binfileLimitSize "10000"

CFG_PRODUCT_NV_BIN_MODEM_NUNBER := /bin_modem_number "3"

CFG_PRODUCT_COMMON_NV_FILE_FORMAT := /common_nv_file_format "1"

CFG_PRODUCT_XML_FOLDER_HIONE := 1

CFG_PRODUCT_NV_COMPRESS := /compress_nv_file "1"

CFG_PRODUCT_NV_XNV_PDT_VERSION := charlotte

CFG_PRODUCT_NV_PARSE_CUSTOMIZE := /parse_customize "1"

CFG_DIAG_SEC_TOOLS := YES

CFG_PRODUCT_VERSION_AFTER_B5000 := 1

CFG_PRODUCT_COMMON_NV_INHERIT_BY_PRODUCT := TRUE

CFG_PRODUCT_SPLIT_NV_BUILD := TRUE

CFG_PRODUCT_NV_AGGREGATE_REARRANGE := YES

CFG_FEATURE_BUILD_BOOT_IMAGE := FEATURE_ON

CFG_PRODUCT_NV_SPLIT_COMM_AND_DIFF := YES

CFG_FEATURE_NV_SEC_ON := YES

CFG_PRODUCT_NV_LEN_BYTE_ALIGNED := YES

CFG_PRODUCT_NCFG_DISTINGUISH_MODEM_FEATURE_ON := YES

CFG_PRODUCT_NCFG_INDEPENDENT_FEATURE_NV := YES

CFG_PRODUCT_NCFG_OPEN_PART_STRUCT_CUST_FEATURE := FEATURE_ON

CFG_PRODUCT_OPEN_PART_STRUCT_CUST_FEATURE := FEATURE_ON
