set(CFG_PRODUCT_CONTROL_VERSION "141")

set(CFG_PRODUCT_DIFF_NV_FILTER charlotte_udp)

set(CFG_PRODUCT_NV_FILE_MAX_SIZE binfileLimitSize "10000")

set(CFG_PRODUCT_NV_BIN_MODEM_NUNBER bin_modem_number "3")

set(CFG_PRODUCT_COMMON_NV_FILE_FORMAT common_nv_file_format "1")

set(CFG_PRODUCT_XML_FOLDER_HIONE 1)

set(CFG_PRODUCT_NV_COMPRESS compress_nv_file "1")

set(CFG_PRODUCT_NV_XNV_PDT_VERSION charlotte)

set(CFG_PRODUCT_NV_PARSE_CUSTOMIZE parse_customize "1")

set(CFG_DIAG_SEC_TOOLS YES)

set(CFG_PRODUCT_VERSION_AFTER_B5000 1)

set(CFG_PRODUCT_COMMON_NV_INHERIT_BY_PRODUCT TRUE)

set(CFG_PRODUCT_SPLIT_NV_BUILD TRUE)

set(CFG_PRODUCT_NV_AGGREGATE_REARRANGE YES)

set(CFG_FEATURE_BUILD_BOOT_IMAGE FEATURE_ON)

set(CFG_PRODUCT_NV_SPLIT_COMM_AND_DIFF YES)

set(CFG_FEATURE_NV_SEC_ON YES)

set(CFG_PRODUCT_NV_LEN_BYTE_ALIGNED YES)

set(CFG_PRODUCT_NCFG_DISTINGUISH_MODEM_FEATURE_ON YES)

set(CFG_PRODUCT_NCFG_INDEPENDENT_FEATURE_NV YES)

set(CFG_PRODUCT_NCFG_OPEN_PART_STRUCT_CUST_FEATURE FEATURE_ON)

set(CFG_PRODUCT_OPEN_PART_STRUCT_CUST_FEATURE FEATURE_ON)

