#ifndef __DDR_DEFINE_SUB_H__
#define __DDR_DEFINE_SUB_H__ 
#define SOC_ACPU_SCTRL_BASE_ADDR (0xFA89B000)
#define SOC_ACPU_TIMER5_BASE_ADDR (0xFA885000)
#define SOC_ACPU_DMCPACK0_BASE_ADDR (0xFFE00000)
#define SOC_ACPU_DMSS_BASE_ADDR (0xFFE80000)
#define DDR_DMSS_BASE_ADDR SOC_ACPU_DMSS_BASE_ADDR
#define DDR_DMCPACK0_BASE_ADDR SOC_ACPU_DMCPACK0_BASE_ADDR
#define DDR_REG_DMC(n) (DDR_DMCPACK0_BASE_ADDR + DDR_REG_CHANNEL_OFFSET(n) + 0x4000UL)
#define DDR_REG_DMSS (DDR_DMSS_BASE_ADDR)
#define DDR_REG_CHANNEL_OFFSET(n) (0x20000UL * (n))
#ifndef REG_BASE_DMSS
#define REG_BASE_DMSS DDR_REG_DMSS
#endif
#define DDRC_REG_DMC(n) (DDR_REG_DMC(n))
#define DDR_REG_DMC_CFG(n) (DDRC_REG_DMC(n))
#endif
