#ifndef __DEBUG_FAULT_INJECTION_H__
#define __DEBUG_FAULT_INJECTION_H__ 
enum FAULT_INJECT_ID {
 XLOADER_FAULT_UFS = 0x1,
 XLOADER_FAULT_DDR,
 XLOADER_FAULT_GPIO,
 KERNEL_FAULT_USB_CLK = 0x50,
 KERNEL_FAULT_USB_POWER,
 KERNEL_FAULT_PCIE,
 KERNEL_FAULT_CLOCK,
 KERNEL_FAULT_HWSPINLOCK,
 KERNEL_FAULT_I2C,
 KERNEL_FAULT_SPI,
 KERNEL_FAULT_UART,
 FAULT_INJECT_MAX = 0xFF,
};
#endif
