#ifndef __LP_GPU_SMC_SERVICES_ID_H__
#define __LP_GPU_SMC_SERVICES_ID_H__ 
enum lp_gpu_smc_idx {
 BL2_GPU_PWRON,
 BL2_GPU_PWROFF,
 BL2_GPU_SET_FREQ,
 BL2_GPU_GET_FREQ,
 BL2_GPU_SET_VOLT,
 BL2_GPU_GET_VOLT,
 BL2_GPU_GET_AVL_FREQ,
 BL2_GPU_FREQ_RANGE_BIAS,
 BL2_GPU_LOGIC_VOLT_BIAS,
 BL2_GPU_MEM_VOLT_BIAS,
 BL2_GPU_PREPROCESS,
 BL2_GPU_SVFD_INIT,
 BL2_GPU_SVFD_TRIM,
 BL2_GPU_SVFD_SWITCH,
 BL2_GPU_SVFD_GET_CODE,
 BL2_GPU_SVFD_EN_MON,
 BL2_GPU_SVFD_GET_CONFIG,
 BL2_GPU_UNIT_TEST,
 BL2_GPU_SMC_IDX_MAX,
};
#endif
