obj-$(CONFIG_HW_WIFI_CLOCK)  += wifi_clock/
obj-y += \
	amax_multilink_interface.o \
	amax_multilink_dev.o \

obj-m += amax.o
amax-objs := amax_multilink_main.o amax_multilink_stat.o amax_multilink_tool.o