#
# Makefile for kernel vendor pcie.
#

obj-$(CONFIG_HIPCIE_CORE) += hi_pcie_core.o
obj-$(CONFIG_HIPCIE_CORE) += hi_pcie_common.o
obj-$(CONFIG_HIPCIE_CORE) += hi_pcie_internal_api.o
obj-$(CONFIG_HIPCIE_CORE) += hi_pcie_external_api.o
obj-$(CONFIG_HIPCIE_CORE) += hi_pcie_msi.o
obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ctrl.o
obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ctrl_rc.o
obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ctrl_ep.o
obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ctrl_dma.o
obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ctrl_common.o
obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ctrl_int.o
obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ep_driver.o
obj-$(CONFIG_HIPCIE_PHY)  += hi_pcie_kphy.o
obj-$(CONFIG_HIPCIE_PHY)  += hi_pcie_combphy.o
obj-$(CONFIG_HIPCIE_IDLE) += hi_pcie_idle.o
obj-$(CONFIG_HIPCIE_CORE) += platform/
obj-$(CONFIG_HIPCIE_TEST) += hi_pcie_test.o
obj-$(CONFIG_HIPCIE_CTRL) += hi_pcie_ctrl_dfx.o
obj-$(CONFIG_HIPCIE_CORE) += hi_pcie_adapter.o
obj-$(CONFIG_HIPCIE_SLT)  += hi_pcie_slt.o
obj-$(CONFIG_HIPCIE_TRAP_HOST)  += hi_pcie_trap_host.o
