# In case the platform does NOT support this type of sensors

obj-m	+= ap_sensor_channel.o
obj-m	+= ap_sensor_route.o
obj-m	+= ap_motion_route.o
obj-m	+= ap_motion_channel.o
obj-m	+= ar_sensor_channel.o
obj-m	+= ar_sensor_route.o
obj-m	+= smart_ar.o
obj-m	+= smart_flp.o
obj-m	+= smart_flp_dt.o
obj-m	+= smart_softtimer.o
