obj-m := awhaptic.o
awhaptic-y :=  aw86907/aw869xx.o aw_vibrator/aw8692x.o aw_vibrator/haptic_hv.o haptic_common.o vibrator_event.o

obj-$(CONFIG_HUAWEI_VIBRATOR) += aw01624/
obj-$(CONFIG_HUAWEI_PMI_LDO_VIBRATOR) += pmi_ldo_vibrator/
