#ifndef __H_TEST_SR_H__
#define __H_TEST_SR_H__ 
#ifdef CONFIG_TEST_SYS_STATE
enum srtest_cmd {
 SRTEST_CMD_REQUEST_NORMAL_BY_LPMCU,
 SRTEST_CMD_RELEASE_NORMAL_BY_LPMCU,
 SRTEST_CMD_SET_TIMER40_TIMEOUT,
 SRTEST_CMD_REQUEST_STANDBY_BY_LPMCU,
 SRTEST_CMD_RELEASE_STANDBY_BY_LPMCU,
 SRTEST_CMD_REQUEST_LIGHTSLEEP,
 SRTEST_CMD_RELEASE_LIGHTSLEEP,
 SRTEST_CMD_SET_WAKEUP_AP_DIRECT,
 SRTEST_CMD_MAX,
};
struct srtest_data {
 unsigned char cmd;
 unsigned char para[4];
};
#endif
#endif
