# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_HUAWEI_POWER_GLINK) += power_glink_module.o

power_glink_module-y := power_glink.o
power_glink_module-y += power_glink_handle_charge.o
power_glink_module-y += power_glink_handle_usb.o

obj-$(CONFIG_HUAWEI_POWER_GLINK_INTERFACE) += power_glink_interface.o

obj-$(CONFIG_HUAWEI_POWER_GLINK) += glink_ulog/
