obj-$(CONFIG_CRYPTO_HICRYPTO) += hicrypto.o

hicrypto-objs := hicrypto_driver.o hicrypto_dev.o

hicrypto-$(CONFIG_CRYPTO_HICRYPTO_SHA) += hicrypto_hash.o
hicrypto-$(CONFIG_CRYPTO_HICRYPTO_CIPHER) += hicrypto_cipher.o
hicrypto-$(CONFIG_CRYPTO_HICRYPTO_AEAD) += hicrypto_aead.o
