-include $(srctree)/drivers/platform_drivers/modem/drv/product_config/product_config.mk

KBUILD_CPPFLAGS += -I$(srctree)/drivers/platform_drivers/modem/drv/omserver/mprobe

obj-y += mprobe_init.o
obj-y += mprobe_channel_manager.o
obj-y += mprobe_message.o
obj-y += mprobe_port.o
obj-y += mprobe_service.o
obj-y += mprobe_debug.o