#=============================================================================
#  wifi
#=============================================================================
obj-$(CONFIG_WIFI_DELAY_STATISTIC) += ipv4/wifi_delayst.o
obj-$(CONFIG_HN_WIFI) += ipv4/
obj-$(CONFIG_HONOR_MSS_AUTO_CHANGE) += ipv4/
obj-$(CONFIG_HN_BOOSTER) += booster/
obj-$(CONFIG_HN_VSIM) += hnril/
obj-$(CONFIG_CHR_NETLINK_MODULE) += chr/
obj-$(CONFIG_HN_DC_MODULE) += hw_dual_connection/
obj-$(CONFIG_HN_DPIMARK_MODULE) += hw_dpi_mark/
obj-$(CONFIG_HN_WAUDIO_MODULE) += waudio/
obj-$(CONFIG_HN_WIFI_EXT) += wifi_ext_adaptor/
obj-$(CONFIG_HN_NETFILTER_MODULE) += hn_netfilter/
EXTRA_CFLAGS += -Idriver/honor_platform
